### ISSUE TITLE
Importing JSON from Raivo -- UUIDs are blank, Aegis crashes

### ISSUE THREAD

**Issue by gigibytes** [beemdevelopment/Aegis#1144]
### Version

2.1.3

### Source

Google Play

### Vault encryption

Yes (with biometric unlock)

### Device

Pixel 7A

### Android version

Android 13

### ROM

GrapheneOS

### Steps to reproduce

1. Export JSON from Raivo on iOS
2. Translate into Aegis format with jq (UUID field = empty strings, don't know how they should be generated)
3. Import into Aegis.

### What do you expect to happen?

Aegis to import the entries, potentially generating UUIDs itself.

### What happens instead?

Aegis crashes.

There is also an issue here that seems to be the same problem: https://github.com/beemdevelopment/Aegis/issues/11 but I am not sure what the solution is.

### Log

Error Info that came up after crash:

- type: crash - osVersion: google/lynx/lynx:13/TQ3A.230605.012/2023061402:user/release-keys - package: com.beemdevelopment.aegis:58 - process: com.beemdevelopment.aegis - processUptime: 27297 + 258 ms - - java.lang.RuntimeException: Unable to start activity ComponentInfo{com.beemdevelopment.aegis/com.beemdevelopment.aegis.ui.ImportEntriesActivity}: java.lang.IllegalArgumentException: Invalid UUID string: - at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3652) - at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3789) - at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101) - at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:138) - at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) - at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2314) - at android.os.Handler.dispatchMessage(Handler.java:106) - at android.os.Looper.loopOnce(Looper.java:201) - at android.os.Looper.loop(Looper.java:288) - at android.app.ActivityThread.main(ActivityThread.java:7937) - at java.lang.reflect.Method.invoke(Native Method) - at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) - at com.android.internal.os.ExecInit.main(ExecInit.java:49) - at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method) - at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355) - Caused by: java.lang.IllegalArgumentException: Invalid UUID string: - at java.util.UUID.fromString(UUID.java:194) - at com.beemdevelopment.aegis.vault.VaultEntry.fromJson(VaultEntry.java:18) - at com.beemdevelopment.aegis.importers.AegisImporter$DecryptedState.convertEntry(AegisImporter.java:1) - at com.beemdevelopment.aegis.importers.AegisImporter$DecryptedState.convert(AegisImporter.java:25) - at com.beemdevelopment.aegis.ui.ImportEntriesActivity.importDatabase(ImportEntriesActivity.java:1) - at com.beemdevelopment.aegis.ui.ImportEntriesActivity.processImporterState(ImportEntriesActivity.java:16) - at com.beemdevelopment.aegis.ui.ImportEntriesActivity.onCreate(ImportEntriesActivity.java:238) - at android.app.Activity.performCreate(Activity.java:8389) - at android.app.Activity.performCreate(Activity.java:8368) - at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1422) - at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3633) - ... 14 more - -

**Comment by alexbakker** [comment]
If you leave out the ``uuid`` field entirely, Aegis will generate one for you. You can also use ``uuidgen`` to generate one yourself.
