### ISSUE TITLE
The application suddenly stops when rotating the screen in the unlock section

### ISSUE THREAD

**Issue by ammarraisafti** [beemdevelopment/Aegis#159]
# Actual behaviour
After entering the password, then rotating the screen, this application must run properly.

# Expected behaviour
The application suddenly stops, after entering the password, then rotates the screen.  Supposedly, that ability must be able to be done.

# Step to reproduce
- Install and open the application. 

- Enter the password, then rotate the screen.

- Then you will find problems like I have experienced.

# Information
- Device: Nubia n2 lite
- Android version: 8.1.0
- Application version: 0.4.3

# Recording of the bug
https://youtu.be/SvXrnsICzE4

**Comment by alexbakker** [comment]
Nice find. We always dismiss the ProgressDialog after SlotListTask is done, but if it has already been dismissed by a device rotation, an exception is thrown.

Here's the stack trace:

```
java.lang.IllegalArgumentException: View=DecorView@6e73996[AuthActivity] not attached to window manager
	at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:485)
	at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:394)
	at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:124)
	at android.app.Dialog.dismissDialog(Dialog.java:375)
	at android.app.Dialog.dismiss(Dialog.java:358)
	at com.beemdevelopment.aegis.ui.tasks.ProgressDialogTask.onPostExecute(ProgressDialogTask.java:32)
	at com.beemdevelopment.aegis.ui.tasks.SlotListTask.onPostExecute(SlotListTask.java:103)
	at com.beemdevelopment.aegis.ui.tasks.SlotListTask.onPostExecute(SlotListTask.java:19)
	at android.os.AsyncTask.finish(AsyncTask.java:695)
	at android.os.AsyncTask.access$600(AsyncTask.java:180)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

We also need to fix this for other activities where ProgressDialogTask is used.
