### ISSUE TITLE
Immediate app crash after start

### ISSUE THREAD

**Issue by hamy4269** [beemdevelopment/Aegis#205]
###### Info

* __Version__: 1.0.0
* __Source__: F-Droid
* __Vault encrypted:__ Yes (with fingerprint unlock)
* __Android version and ROM:__ Android 6.0, EMUI 4.0.3 (Honor 7) 

###### Steps to reproduce

I just started the app after the update to version 1.0.0 from F-Droid.
Downgrading in F-Droid Store to previous version failes.

###### What do you expect to happen?

The app to start.

###### What happens instead?

The login-screen shows up and the app crashes immediately afterwards.

###### Log

Hope the log below helps you to figure out the problem.

```
09-14 13:17:11.339  4446  4446 I HwLauncher:  FPSMonitor [Launcher , dispatchTouchEvent begin, false, true] down event  x = 549 y = 549
09-14 13:17:11.339  4446  4446 I HwLauncher: Launcher  while lockScreenOrientation,isRotationEnabled is false!
09-14 13:17:11.341  4446  4446 I HwLauncher:  FPSMonitor [PagedView , onIntercept] down event  x = 449 y = 449
09-14 13:17:11.345  4446  4446 I HwSecImmHelper: mSecurityInputMethodService is null
09-14 13:17:11.346  4446  4446 I HwLauncher:  FPSMonitor [Launcher , dispatchTouchEvent end, false, true] down event  x = 549 y = 549
09-14 13:17:11.403  4446  4446 I HwLauncher:  FPSMonitor [Launcher , dispatchTouchEvent begin, false, true] up event  x = 549 y = 549
09-14 13:17:11.404  4446  4446 I HwLauncher: QuickActionView hide() animated = true, fromSticky = true
09-14 13:17:11.404  4446  4446 I HwLauncher: QuickActionView hide() action view has already hidden, return.
09-14 13:17:11.404  4446  4446 I HwLauncher: Launcher mUnlockScreenRunnbale  getOrientationEnabled false
09-14 13:17:11.404  4446  4446 I HwLauncher:  FPSMonitor [Launcher , dispatchTouchEvent end, false, true] up event  x = 549 y = 549
09-14 13:17:11.404  4409  4918 W PhoneStateManager: Maybe it's incorrect, actionID:[null]
09-14 13:17:11.405  4446  4446 I HwLauncher: Launcher.Utilities  startActivitySafely useLaunchAnimation = true
09-14 13:17:11.405  4446  4446 I HwLauncher: Launcher.Utilities  startActivitySafely begin startActivity() for current user
09-14 13:17:11.410  4409  4409 I K3V3CpuGovernorPolicy: set scene Hmp policy : 300 , 150
09-14 13:17:11.417  4446  4446 I HwLauncher: Launcher.Utilities  startActivitySafely end startActivity() for current user
09-14 13:17:11.420  4446  4446 I HwLauncher: Launcher onPause()
09-14 13:17:11.421  4446  4969 I HwLauncher: Launcher.MotionManager stopMotionAppsReco begin,flg = 402
09-14 13:17:11.421  4446  4969 W HwLauncher: Launcher.MotionManager stopMotionAppsReco service flg 402 is unavailable
09-14 13:17:11.425  4446  4970 I HwLauncher: Launcher.MotionManager stopMotionAppsReco begin,flg = 403
09-14 13:17:11.426  4446  4970 W HwLauncher: Launcher.MotionManager stopMotionAppsReco service flg 403 is unavailable
09-14 13:17:11.437  4971  4971 I         : power log dlsym ok
09-14 13:17:11.439  4446  4446 I TotemWeather: AbstractDualWeatherWidgetHomeView onWindowFocusChanged, hasWindowFocus= false
09-14 13:17:11.455  2859  3060 I [Gralloc]: alloc w[1080] h[1920] format[1] usage[2355]
09-14 13:17:11.455  2859  2931 I [Gralloc]: alloc w[1080] h[1920] format[1] usage[3]
09-14 13:17:11.455  2859  3060 I [Gralloc]: alloc succ handle[0x5590f33780] stride[1120]
09-14 13:17:11.460  2859  2931 I [Gralloc]: alloc succ handle[0x5590ee5110] stride[1120]
09-14 13:17:11.481  4409  4949 W PGApi_client: recv actoionId = 10000, action = com.huawei.pgmng.PGAction@98d81bd actionId =10000 pkg =com.beemdevelopment.aegis extend1 =51354 extend2 = flag =3 type =1
09-14 13:17:11.481  4409  4949 W PGMiddleWare: in handleAction method, action = 10000
09-14 13:17:11.481  4409  4949 W PGMiddleWare: in handleAction, invoke client = com.huawei.pgmng.middleware.AudioEffectLowPowerImpl@5c38860, action = com.huawei.pgmng.PGAction@98d81bd actionId =10000 pkg =com.beemdevelopment.aegis extend1 =51354 extend2 = flag =3 type =1
09-14 13:17:11.490  4069  4533 I HwSystemManager: NotificationGuideService:handle MSG_ACTIVIY_FOREGROUND, uid:10304
09-14 13:17:11.495  2859  3060 I [Gralloc]: alloc w[16] h[16] format[1] usage[256]
09-14 13:17:11.496  2859  3060 I [Gralloc]: alloc succ handle[0x5590d03a60] stride[32]
09-14 13:17:11.497  4971  4983 E linker  : readlink('/proc/self/fd/20') failed: Permission denied [fd=20]
09-14 13:17:11.497  4971  4983 E linker  : warning: unable to get realpath for the library "/system/lib64/hw/gralloc.hi3635.so". Will use given name.
09-14 13:17:11.498  4971  4983 E linker  : readlink('/proc/self/fd/20') failed: Permission denied [fd=20]
09-14 13:17:11.498  4971  4983 E linker  : warning: unable to get realpath for the library "libion.so". Will use given name.
09-14 13:17:11.499  4971  4983 E HAL     : load: id=gralloc != hmi->id=gralloc
09-14 13:17:11.508  4971  4971 W System  : ClassLoader referenced unknown path: /data/app/com.beemdevelopment.aegis-2/lib/arm64
09-14 13:17:11.553  4971  4971 I HwCust  : Constructor found for class android.app.HwCustHwWallpaperManagerImpl
09-14 13:17:11.566  4971  4971 W art     : Before Android 4.1, method android.graphics.PorterDuffColorFilter androidx.vectordrawable.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
09-14 13:17:11.602  4971  4971 I art     : Rejecting re-init on previously-failed class java.lang.Class<androidx.core.view.ViewCompat$OnUnhandledKeyEventListenerWrapper>
09-14 13:17:11.602  4971  4971 I art     : Rejecting re-init on previously-failed class java.lang.Class<androidx.core.view.ViewCompat$OnUnhandledKeyEventListenerWrapper>
09-14 13:17:11.923  2875  2875 I HisiKeyMaster: hisi_km_get_key_characteristics start
09-14 13:17:11.926  2875  2875 I HisiKeyMaster: hisi_km_get_key_characteristics success
09-14 13:17:11.930  2875  2875 I HisiKeyMaster: hisi_km_get_key_characteristics start
09-14 13:17:11.933  2875  2875 I HisiKeyMaster: hisi_km_get_key_characteristics success
09-14 13:17:11.933  2875  2875 I HisiKeyMaster: hisi_km_begin start
09-14 13:17:11.939  2875  2875 I HisiKeyMaster: out_params_buffer_len = 32
09-14 13:17:11.939  2875  2875 I HisiKeyMaster: hisi_km_begin success
09-14 13:17:11.940  2875  2875 I HisiKeyMaster: hisi_km_get_key_characteristics start
09-14 13:17:11.942  2875  2875 I HisiKeyMaster: hisi_km_get_key_characteristics success
09-14 13:17:11.944  3202  3202 I fingerprintd: FingerprintDaemonProxyEx::onTransact, code:7
09-14 13:17:11.944  3202  3855 I fpc_fingerprint_hal: fpc wait irq over
09-14 13:17:11.944  3202  3855 I fpc_tac : fpc_tac_send_cmd cmd:65536, data:1
09-14 13:17:11.970  3202  3855 I fpc_tac : fpc_tac_send_cmd:ok, response:0
09-14 13:17:11.970  3202  3202 I fpc_tac : fpc_tac_send_get_uint64_cmd cmd:39, data:0
09-14 13:17:11.973  3202  3202 I fpc_tac : fpc_tac_send_get_uint64_cmd:ok, response:0
09-14 13:17:11.973  3202  3855 I fpc_tac : fpc_tac_send_cmd cmd:65536, data:1
09-14 13:17:11.975  2875  2875 I HisiKeyMaster: hisi_km_get_key_characteristics start
09-14 13:17:11.978  2875  2875 I HisiKeyMaster: hisi_km_get_key_characteristics success
09-14 13:17:11.978  2875  2875 I HisiKeyMaster: hisi_km_begin start
09-14 13:17:11.990  2875  2875 I HisiKeyMaster: out_params_buffer_len = 0
09-14 13:17:11.990  2875  2875 I HisiKeyMaster: hisi_km_begin success
09-14 13:17:11.991  2875  2875 I HisiKeyMaster: hisi_km_get_key_characteristics start
09-14 13:17:11.994  2875  2875 I HisiKeyMaster: hisi_km_get_key_characteristics success
09-14 13:17:11.996  3202  3202 I fingerprintd: FingerprintDaemonProxyEx::onTransact, code:7
09-14 13:17:12.011  3202  3855 I fpc_tac : fpc_tac_send_cmd:ok, response:0
09-14 13:17:12.011  3202  3202 I fpc_tac : fpc_tac_send_get_uint64_cmd cmd:39, data:0
09-14 13:17:12.014  3202  3202 I fpc_tac : fpc_tac_send_get_uint64_cmd:ok, response:0
09-14 13:17:12.014  3202  3855 I fpc_tac : fpc_tac_send_cmd cmd:65536, data:1
09-14 13:17:12.019  3202  3202 I fingerprintd: FingerprintDaemonProxyEx::onTransact, code:1
09-14 13:17:12.036  4971  4971 I HwSecImmHelper: mSecurityInputMethodService is null
09-14 13:17:12.055  3202  3855 I fpc_tac : fpc_tac_send_cmd:ok, response:0
09-14 13:17:12.055  3202  3855 I fpc_tac : fpc_tac_send_get_uint32_cmd cmd:18, data:0
09-14 13:17:12.058  3202  3855 I fpc_tac : fpc_tac_send_get_uint32_cmd:ok, response:0
09-14 13:17:12.058  3202  3855 I fpc_tac : fpc_tac_send_get_indices_cmd indices:0x55cccd6c50, index_count:2
09-14 13:17:12.061  3202  3855 I fpc_tac : fpc_tac_send_get_indices_cmd:ok, response:0
09-14 13:17:12.061  3202  3855 I fpc_tac : Number of indices in the database: 2
09-14 13:17:12.061  3202  3855 I fpc_tac : indices[0]:0, indices[1]:1
09-14 13:17:12.061  3202  3855 I fpc_tac : fpc_tac_send_set_uint64_cmd cmd:43, data:h ced489ee l 8c7f768f
09-14 13:17:12.068  3202  3855 I fpc_tac : fpc_tac_send_set_uint64_cmd:ok, response:0
09-14 13:17:12.068  3202  3855 I fpc_tac : fpc_tac_send_set_arbitrary_data_cmd cmd:7, param:0, data:0x55cccd6c50, data_size:8
09-14 13:17:12.077  3202  3855 I fpc_tac : fpc_tac_send_set_arbitrary_data_cmd:ok, response:0
09-14 13:17:12.077  3202  3855 I fpc_tac : fpc_tac_send_get_uint32_cmd cmd:21, data:0
09-14 13:17:12.101  4971  4987 E HAL     : load: id=gralloc != hmi->id=gralloc
09-14 13:17:12.102  4971  4987 I OpenGLRenderer: Initialized EGL, version 1.4
09-14 13:17:12.105  4971  4987 E linker  : readlink('/proc/self/fd/29') failed: Permission denied [fd=29]
09-14 13:17:12.105  4971  4987 E linker  : warning: unable to get realpath for the library "libhwaps.so". Will use given name.
09-14 13:17:12.110  4971  4987 E linker  : readlink('/proc/self/fd/30') failed: Permission denied [fd=30]
09-14 13:17:12.110  4971  4987 E linker  : warning: unable to get realpath for the library "/system/lib64/libhwuibp.so". Will use given name.
09-14 13:17:12.115  2859  3059 I [Gralloc]: alloc w[1080] h[1920] format[1] usage[2816]
09-14 13:17:12.121  2859  3059 I [Gralloc]: alloc succ handle[0x5590e8e850] stride[1120]
09-14 13:17:12.121  2859  3059 I [Gralloc]: alloc w[1080] h[1920] format[1] usage[2816]
09-14 13:17:12.126  2859  3059 I [Gralloc]: alloc succ handle[0x5590d01280] stride[1120]
09-14 13:17:12.126  2859  3059 I [Gralloc]: alloc w[1080] h[1920] format[1] usage[2816]
09-14 13:17:12.131  2859  3059 I [Gralloc]: alloc succ handle[0x5590eb0540] stride[1120]
09-14 13:17:12.143  3202  3855 I fpc_tac : fpc_tac_send_get_uint32_cmd:ok, response:0
09-14 13:17:12.177  3395  3416 I ActivityManager: Displayed com.beemdevelopment.aegis/.ui.AuthActivity: +349ms (total +754ms)
09-14 13:17:12.186  4409  4409 I K3V3CpuGovernorPolicy: close previously scene Hmp policy : 300 , 150
09-14 13:17:12.203  4971  4971 W SupportMenuInflater: Cannot instantiate class: android.widget.SearchView
09-14 13:17:12.203  4971  4971 W SupportMenuInflater: java.lang.reflect.InvocationTargetException
09-14 13:17:12.203  4971  4971 W SupportMenuInflater:   at java.lang.reflect.Constructor.newInstance(Native Method)
09-14 13:17:12.203  4971  4971 W SupportMenuInflater:   at androidx.appcompat.view.SupportMenuInflater$MenuState.newInstance(SupportMenuInflater.java:551)
09-14 13:17:12.203  4971  4971 W SupportMenuInflater:   at androidx.appcompat.view.SupportMenuInflater$MenuState.setItem(SupportMenuInflater.java:496)
09-14 13:17:12.203  4971  4971 W SupportMenuInflater:   at androidx.appcompat.view.SupportMenuInflater$MenuState.addItem(SupportMenuInflater.java:530)
09-14 13:17:12.203  4971  4971 W SupportMenuInflater:   at androidx.appcompat.view.SupportMenuInflater.parseMenu(SupportMenuInflater.java:206)
09-14 13:17:12.203  4971  4971 W SupportMenuInflater:   at androidx.appcompat.view.SupportMenuInflater.inflate(SupportMenuInflater.java:128)
09-14 13:17:12.203  4971  4971 W SupportMenuInflater:   at com.beemdevelopment.aegis.ui.MainActivity.onCreateOptionsMenu(MainActivity.java:509)
09-14 13:17:12.203  4971  4971 W SupportMenuInflater:   at android.app.Activity.onCreatePanelMenu(Activity.java:2946)
09-14 13:17:12.203  4971  4971 W SupportMenuInflater:   at androidx.fragment.app.FragmentActivity.onCreatePanelMenu(FragmentActivity.java:378)
09-14 13:17:12.203  4971  4971 W SupportMenuInflater:   at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:94)
09-14 13:17:12.203  4971  4971 W SupportMenuInflater:   at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.onCreatePanelMenu(AppCompatDelegateImpl.java:2549)
09-14 13:17:12.203  4971  4971 W SupportMenuInflater:   at androidx.appcompat.app.AppCompatDelegateImpl.preparePanel(AppCompatDelegateImpl.java:1589)
09-14 13:17:12.203  4971  4971 W SupportMenuInflater:   at androidx.appcompat.app.AppCompatDelegateImpl.doInvalidatePanelMenu(AppCompatDelegateImpl.java:1869)
09-14 13:17:12.203  4971  4971 W SupportMenuInflater:   at androidx.appcompat.app.AppCompatDelegateImpl$2.run(AppCompatDelegateImpl.java:230)
09-14 13:17:12.203  4971  4971 W SupportMenuInflater:   at android.os.Handler.handleCallback(Handler.java:743)
09-14 13:17:12.203  4971  4971 W SupportMenuInflater:   at android.os.Handler.dispatchMessage(Handler.java:95)
09-14 13:17:12.203  4971  4971 W SupportMenuInflater:   at android.os.Looper.loop(Looper.java:150)
09-14 13:17:12.203  4971  4971 W SupportMenuInflater:   at android.app.ActivityThread.main(ActivityThread.java:5621)
09-14 13:17:12.203  4971  4971 W SupportMenuInflater:   at java.lang.reflect.Method.invoke(Native Method)
09-14 13:17:12.203  4971  4971 W SupportMenuInflater:   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
09-14 13:17:12.203  4971  4971 W SupportMenuInflater:   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684)
09-14 13:17:12.203  4971  4971 W SupportMenuInflater: Caused by: android.view.InflateException: Binary XML file line #79: Binary XML file line #79: Error inflating class android.widget.SearchView$SearchAutoComplete
09-14 13:17:12.203  4971  4971 W SupportMenuInflater:   at android.view.LayoutInflater.inflate(LayoutInflater.java:558)
09-14 13:17:12.203  4971  4971 W SupportMenuInflater:   at com.mikepenz.iconics.context.InternalLayoutInflater.inflate(InternalLayoutInflater.java:81)
09-14 13:17:12.203  4971  4971 W SupportMenuInflater:   at android.view.LayoutInflater.inflate(LayoutInflater.java:434)
09-14 13:17:12.203  4971  4971 W SupportMenuInflater:   at android.widget.SearchView.inflateSearchView(SearchView.java:1847)
09-14 13:17:12.203  4971  4971 W SupportMenuInflater:   at android.widget.SearchView.<init>(SearchView.java:268)
09-14 13:17:12.203  4971  4971 W SupportMenuInflater:   at android.widget.SearchView.<init>(SearchView.java:259)
09-14 13:17:12.203  4971  4971 W SupportMenuInflater:   at android.widget.SearchView.<init>(SearchView.java:255)
09-14 13:17:12.203  4971  4971 W SupportMenuInflater:   at android.widget.SearchView.<init>(SearchView.java:251)
09-14 13:17:12.203  4971  4971 W SupportMenuInflater:   ... 21 more
09-14 13:17:12.203  4971  4971 W SupportMenuInflater: Caused by: android.view.InflateException: Binary XML file line #79: Error inflating class android.widget.SearchView$SearchAutoComplete
09-14 13:17:12.203  4971  4971 W SupportMenuInflater:   at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:801)
09-14 13:17:12.203  4971  4971 W SupportMenuInflater:   at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:723)
09-14 13:17:12.203  4971  4971 W SupportMenuInflater:   at android.view.LayoutInflater.rInflate(LayoutInflater.java:854)
09-14 13:17:12.203  4971  4971 W SupportMenuInflater:   at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:817)
09-14 13:17:12.203  4971  4971 W SupportMenuInflater:   at android.view.LayoutInflater.rInflate(LayoutInflater.java:857)
09-14 13:17:12.203  4971  4971 W SupportMenuInflater:   at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:817)
09-14 13:17:12.203  4971  4971 W SupportMenuInflater:   at android.view.LayoutInflater.rInflate(LayoutInflater.java:857)
09-14 13:17:12.203  4971  4971 W SupportMenuInflater:   at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:817)
09-14 13:17:12.203  4971  4971 W SupportMenuInflater:   at android.view.LayoutInflater.inflate(LayoutInflater.java:534)
09-14 13:17:12.203  4971  4971 W SupportMenuInflater:   ... 28 more
09-14 13:17:12.203  4971  4971 W SupportMenuInflater: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.widget.SearchView.isInActionMode()' on a null object reference
09-14 13:17:12.203  4971  4971 W SupportMenuInflater:   at android.widget.SearchView$SearchAutoComplete.enoughToFilter(SearchView.java:1801)
09-14 13:17:12.203  4971  4971 W SupportMenuInflater:   at android.widget.AutoCompleteTextView.doAfterTextChanged(AutoCompleteTextView.java:781)
09-14 13:17:12.203  4971  4971 W SupportMenuInflater:   at android.widget.AutoCompleteTextView$MyWatcher.afterTextChanged(AutoCompleteTextView.java:749)
09-14 13:17:12.203  4971  4971 W SupportMenuInflater:   at android.widget.TextView.sendAfterTextChanged(TextView.java:8232)
09-14 13:17:12.203  4971  4971 W SupportMenuInflater:   at android.widget.TextView.setText(TextView.java:4435)
09-14 13:17:12.203  4971  4971 W SupportMenuInflater:   at android.widget.TextView.setText(TextView.java:4283)
09-14 13:17:12.203  4971  4971 W SupportMenuInflater:   at android.widget.EditText.setText(EditText.java:84)
09-14 13:17:12.203  4971  4971 W SupportMenuInflater:   at android.widget.TextView.setText(TextView.java:4258)
09-14 13:17:12.203  4971  4971 W SupportMenuInflater:   at com.mikepenz.iconics.Iconics$IconicsBuilderView.build(
09-14 13:17:12.215  3395  3410 W System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'int com.huawei.lcagent.client.LogCollectManager.getUserType()' on a null object reference
09-14 13:17:12.215  3395  3410 W System.err:    at com.android.server.util.ReportTools.getUserType(ReportTools.java:86)
09-14 13:17:12.215  3395  3410 W System.err:    at com.android.server.util.ReportTools.isBetaUser(ReportTools.java:73)
09-14 13:17:12.215  3395  3410 W System.err:    at com.android.server.util.ReportTools.report(ReportTools.java:58)
09-14 13:17:12.215  3395  3410 W System.err:    at com.android.server.util.HwUserBehaviourRecord.appExitRecord(HwUserBehaviourRecord.java:65)
09-14 13:17:12.215  3395  3410 W System.err:    at com.android.server.am.ActivityManagerService$UiHandler.handleMessage(ActivityManagerService.java:1576)
09-14 13:17:12.215  3395  3410 W System.err:    at android.os.Handler.dispatchMessage(Handler.java:102)
09-14 13:17:12.215  3395  3410 W System.err:    at android.os.Looper.loop(Looper.java:150)
09-14 13:17:12.215  3395  3410 W System.err:    at android.os.HandlerThread.run(HandlerThread.java:61)
09-14 13:17:12.215  3395  3410 W System.err:    at com.android.server.ServiceThread.run(ServiceThread.java:46)
09-14 13:17:12.215  3395  3410 E ReportTools: This is not beta user build
09-14 13:17:12.216  4971  4971 I Process : Sending signal. PID: 4971 SIG: 9
09-14 13:17:12.216  4409 19079 I PgedBinderListener: kstate callback type:8 value1=4971 value2=KILLED
09-14 13:17:12.217  3205  3383 I logserver: handle_logfile_events, Object Path:/data/system/dropbox/, mask=0x00000080
09-14 13:17:12.217  3205  3383 I logserver: process_one_event, event->len=48, name=data_app_crash@1568459832216.txt
09-14 13:17:12.217  3205  3383 I logserver: find_first_match: find match, plogs(type=1, pfile=/data/system/dropbox/, match=app_crash)
09-14 13:17:12.217  3395  3395 I SendBroadcastPermission: action:android.intent.action.DROPBOX_ENTRY_ADDED, mPermissionType:0
09-14 13:17:12.218  2857  2857 E lowmemorykiller: Error writing /proc/4971/oom_score_adj; errno=22
09-14 13:17:12.221  3205  3383 I logserver: is_all_ready, any file is ready in non-keyfile exception.
09-14 13:17:12.221  3205  3383 I logserver: extract_appname, forward search, appname=com.beemdevelopment.aegis
09-14 13:17:12.221  3205  3383 I logserver: archive_and_send, pos=0, type=crash, output=20190914131712_crash
09-14 13:17:12.221  3205  3383 I logserver: ---copy_match_files enter!!--
09-14 13:17:12.222  3205  3383 I logserver: [copy_match_files,864]: copy [/data/system/dropbox/data_app_crash@1568459832216.txt] to [/data/log/logcache/-152663760/data_app_crash@1568459832216.txt]
09-14 13:17:12.222  3205  3383 I logserver: get_fault_appname, appname=com.beemdevelopment.aegis
09-14 13:17:12.222  3205  3383 I logserver: handle_archive_exception, BASIC_MODE
09-14 13:17:12.222  3205  3383 I logserver: remove_last_modify_file, into 1 times, file_dir:
09-14 13:17:12.222  3205  3383 I logserver: remove_last_modify_file, into 1 times, file_dir:
09-14 13:17:12.222  3205  3383 I logserver: get_disk_available_size, Disk_available = 1257553920 B = 1199 MB
09-14 13:17:12.222  3205  3383 I logserver: pack_files, output_path is /data/log/unzip.
09-14 13:17:12.222  3205  3383 I logserver: move_input_files, create dir [/data/log/unzip/PLK-L01_PLK-L01C432B396_0000000000_20190914131712_crash]
09-14 13:17:12.223  3205  3383 I logserver: handle_archive_exception, into set notify_type
09-14 13:17:12.223  3205  3383 I logserver: get_notify_mode, 1
09-14 13:17:12.223  3205  3383 I logserver: Process 3383 opened FIFO(10) for O_WRONLY
09-14 13:17:12.223  3205  3383 I logserver: notify_logcontrol, 3383 sent /data/log/unzip/PLK-L01_PLK-L01C432B396_0000000000_20190914131712_crash
09-14 13:17:12.223  3205  3383 I logserver: check_dir_size, dir[/data/log/coredump/] doesn't exist
09-14 13:17:12.223  3205  3205 I logserver: process_event
09-14 13:17:12.223  3205  3383 I logserver: clean_cur_cache:999, system(rm -r /data/log/logcache/-152663760/* > /dev/null 2>&1)
09-14 13:17:12.223  3205  3205 I logserver: handle_fifo_msg, read res = 460, client pid = 3383, command = send log, data=/data/log/unzip/PLK-L01_PLK-L01C432B396_0000000000_20190914131712_crash
09-14 13:17:12.223  3205  3205 I logserver: handle_fifo_msg, 3383 sent /data/log/unzip/PLK-L01_PLK-L01C432B396_0000000000_20190914131712_crash
09-14 13:17:12.223  3205  3382 I logserver: thread_logcontrol: /data/log/logcontrol has changed.
09-14 13:17:12.224  3205  3382 I logserver: handle_notify_event, send msg [submit:trigger=0,bugtype=2,modulename=com.beemdevelopment.aegis,level=1,testtype=NORMAL,path=/data/log/unzip/PLK-L01_PLK-L01C432B396_0000000000_20190914131712_crash,mode=1;]
09-14 13:17:12.224  3205  3382 I logserver: send_to_client, send to (9) res = 172
09-14 13:17:12.287  3395  4648 I AccountManagerService: getTypesVisibleToCaller: isPermitted? true
09-14 13:17:12.288  4821  4841 W DeviceInfoFile: !devFile.exists()
```

**Comment by michaelschattgen** [comment]
Hi Hamy, thanks for your bug report! We've already fixed this bug (which only occurred on Huawei devices) in https://github.com/beemdevelopment/Aegis/commit/85bf4adc723a6395bba0d93867d3baf92de4f830 and we've made a release 3 days ago. 

F-Droid is just *very* slow on fetching new updates. You can download our latest release from [here](https://github.com/beemdevelopment/Aegis/releases) or you can wait until F-Droid picks up our latest update.

I'm closing it now since we've already fixed it.

**Comment by hamy4269** [comment]
That is great to hear! Thank you.
