### ISSUE TITLE
Crash when reconfiguring biometric authentication

### ISSUE THREAD

**Issue by Vstory** [beemdevelopment/Aegis#332]
###### Info

* Version: 1.1.4
* Source: Google Play
* Vault encrypted: Yes/ biometric unlock
* Device:XiaoMi Note 3
* Android version and ROM:MIUI 11 20.3.12

###### Steps to reproduce
1.Enter "Aegis" settings;
2.Turn off biometric unlock;
3.Crash when opening biometric unlock.

###### What happens instead?

Crash when reconfiguring biometric authentication.

###### Log

```
java.security.ProviderException: Keystore operation failed
	at android.security.keystore.AndroidKeyStoreKeyGeneratorSpi.engineGenerateKey(AndroidKeyStoreKeyGeneratorSpi.java:318)
	at javax.crypto.KeyGenerator.generateKey(KeyGenerator.java:612)
	at com.beemdevelopment.aegis.crypto.KeyStoreHandle.generateKey(KeyStoreHandle.java:63)
	at com.beemdevelopment.aegis.helpers.BiometricSlotInitializer.authenticate(BiometricSlotInitializer.java:63)
	at com.beemdevelopment.aegis.ui.PreferencesFragment$10.onPreferenceChange(PreferencesFragment.java:311)
	at androidx.preference.Preference.callChangeListener(Preference.java:1118)
	at androidx.preference.TwoStatePreference.onClick(TwoStatePreference.java:67)
	at androidx.preference.Preference.performClick(Preference.java:1182)
	at androidx.preference.Preference.performClick(Preference.java:1166)
	at androidx.preference.SwitchPreferenceCompat.performClick(SwitchPreferenceCompat.java:193)
	at androidx.preference.Preference$1.onClick(Preference.java:181)
	at android.view.View.performClick(View.java:6608)
	at android.view.View.performClickInternal(View.java:6585)
	at android.view.View.access$3100(View.java:785)
	at android.view.View$PerformClick.run(View.java:25921)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:201)
	at android.app.ActivityThread.main(ActivityThread.java:6821)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
Caused by: android.security.KeyStoreException: User authentication required
	at android.security.KeyStore.getKeyStoreException(KeyStore.java:813)
	... 22 more
```

```
java.security.ProviderException: Keystore operation failed
	at android.security.keystore.AndroidKeyStoreKeyGeneratorSpi.engineGenerateKey(AndroidKeyStoreKeyGeneratorSpi.java:318)
	at javax.crypto.KeyGenerator.generateKey(KeyGenerator.java:612)
	at com.beemdevelopment.aegis.crypto.KeyStoreHandle.generateKey(KeyStoreHandle.java:63)
	at com.beemdevelopment.aegis.helpers.BiometricSlotInitializer.authenticate(BiometricSlotInitializer.java:63)
	at com.beemdevelopment.aegis.ui.slides.CustomAuthenticatedSlide.showBiometricPrompt(CustomAuthenticatedSlide.java:86)
	at com.beemdevelopment.aegis.ui.slides.CustomAuthenticatedSlide.onSlideSelected(CustomAuthenticatedSlide.java:95)
	at com.github.paolorotolo.appintro.AppIntroBase.handleSlideChanged(AppIntroBase.java:393)
	at com.github.paolorotolo.appintro.AppIntroBase.access$600(AppIntroBase.java:41)
	at com.github.paolorotolo.appintro.AppIntroBase$PagerOnPageChangeListener.onPageSelected(AppIntroBase.java:1124)
	at androidx.viewpager.widget.ViewPager.dispatchOnPageSelected(ViewPager.java:1947)
	at androidx.viewpager.widget.ViewPager.scrollToItem(ViewPager.java:686)
	at androidx.viewpager.widget.ViewPager.setCurrentItemInternal(ViewPager.java:670)
	at androidx.viewpager.widget.ViewPager.setCurrentItemInternal(ViewPager.java:631)
	at androidx.viewpager.widget.ViewPager.setCurrentItem(ViewPager.java:612)
	at com.github.paolorotolo.appintro.AppIntroViewPager.setCurrentItem(AppIntroViewPager.java:84)
	at com.github.paolorotolo.appintro.AppIntroViewPager.goToNextSlide(AppIntroViewPager.java:47)
	at com.github.paolorotolo.appintro.AppIntroBase.changeSlide(AppIntroBase.java:965)
	at com.github.paolorotolo.appintro.AppIntroBase.access$300(AppIntroBase.java:41)
	at com.github.paolorotolo.appintro.AppIntroBase$NextButtonOnClickListener.onClick(AppIntroBase.java:1059)
	at android.view.View.performClick(View.java:6608)
	at android.view.View.performClickInternal(View.java:6585)
	at android.view.View.access$3100(View.java:785)
	at android.view.View$PerformClick.run(View.java:25921)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:201)
	at android.app.ActivityThread.main(ActivityThread.java:6821)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
Caused by: android.security.KeyStoreException: User authentication required
	at android.security.KeyStore.getKeyStoreException(KeyStore.java:813)
	... 30 more
```

**Comment by Vstory** [comment]
Choosing biometrics in the wizard will also crash.
I cannot select biometrics in the trial interface or the application will crash.

Install "Aegis" for the first time and choose password encryption.After that, I can turn on biometric authentication in the "Aegis" settings, but it didn't take long to prompt that the security settings were changed.
Now I can no longer use biometric authentication in "Aegis", uninstalling and reinstalling has no effect

**Comment by Vstory** [comment]
The problem has been resolved, please see:[Adding a new fingerprint displays an error](https://github.com/Kunzisoft/KeePassDX/issues/488)
