### ISSUE TITLE
Crash when importing Authy data with root privileges

### ISSUE THREAD

**Issue by Vstory** [beemdevelopment/Aegis#333]
###### Info

* Version: 1.1.4
* Source: Google Play
* Vault encrypted: Yes/ biometric unlock
* Device:XiaoMi Note 3
* Android version and ROM:MIUI 11 20.3.12

###### Steps to reproduce
1.Choose to import from another application;
2.Select application "Authy";
3.Crash when confirming import

###### Log

```
java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=65540, result=-1, data=Intent { (has extras) }} to activity {com.beemdevelopment.aegis/com.beemdevelopment.aegis.ui.PreferencesActivity}: java.util.UnknownFormatConversionException: Conversion = '!'
	at android.app.ActivityThread.deliverResults(ActivityThread.java:4434)
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4476)
	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1832)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:201)
	at android.app.ActivityThread.main(ActivityThread.java:6821)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
Caused by: java.util.UnknownFormatConversionException: Conversion = '!'
	at java.util.Formatter$FormatSpecifier.conversion(Formatter.java:2781)
	at java.util.Formatter$FormatSpecifier.<init>(Formatter.java:2811)
	at java.util.Formatter$FormatSpecifierParser.<init>(Formatter.java:2624)
	at java.util.Formatter.parse(Formatter.java:2557)
	at java.util.Formatter.format(Formatter.java:2504)
	at java.util.Formatter.format(Formatter.java:2458)
	at java.lang.String.format(String.java:2883)
	at android.content.res.Resources.getString(Resources.java:478)
	at com.beemdevelopment.aegis.ui.PreferencesFragment.onSelectEntriesResult(PreferencesFragment.java:643)
	at com.beemdevelopment.aegis.ui.PreferencesFragment.onActivityResult(PreferencesFragment.java:393)
	at androidx.fragment.app.FragmentActivity.onActivityResult(FragmentActivity.java:170)
	at android.app.Activity.dispatchActivityResult(Activity.java:7590)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:4427)
	... 11 more
```

**Comment by alexbakker** [comment]
I'm unable to reproduce this. Which language is Aegis in on your device?

**Comment by alexbakker** [comment]
We think that this issue was fixed here: https://github.com/beemdevelopment/Aegis/commit/e12bfdbe583cac960c355f5b5626dcd7e05695be#diff-722c6062dd4e87d29cdedf7307d50973. Feel free to reopen if that's not the case.
