### ISSUE TITLE
Enabling Biometrics Fails on Android R DP2

### ISSUE THREAD

**Issue by squabbi** [beemdevelopment/Aegis#374]
I understand that I'm running a developer preview, as I'm doing some testing on my own app, so if this is something you'll end up fixing later on when either the Android beta starts up, or when it is finally released, feel free to close this issue. :)

###### Info

* __Version__: 1.1.4
* __Source__: F-Droid
* __Vault encrypted:__ Yes
* __Device:__ Pixel 3
* __Android version and ROM:__ Android 11 (R) Developer Preview 2

###### Steps to reproduce

Go to Settings and try to enable Biometric unlock on Android R DP2.

###### What do you expect to happen?

For Biometrics to be enabled.

###### What happens instead?

Toast comes up saying there was an Illegal Argument Exception, Int value out of range at -1.

###### Log

```
--------- beginning of main
04-23 10:42:55.764 22579 22601 I AdrenoGLES-0: QUALCOMM build                   : 7fbe12a, I2938829f4a
04-23 10:42:55.764 22579 22601 I AdrenoGLES-0: Build Date                       : 12/02/19
04-23 10:42:55.764 22579 22601 I AdrenoGLES-0: OpenGL ES Shader Compiler Version: EV031.28.07.00
04-23 10:42:55.764 22579 22601 I AdrenoGLES-0: Local Branch                     : gfx-adreno.lnx.1.0
04-23 10:42:55.764 22579 22601 I AdrenoGLES-0: Remote Branch                    : quic/gfx-adreno.lnx.1.0
04-23 10:42:55.764 22579 22601 I AdrenoGLES-0: Remote Branch                    : NONE
04-23 10:42:55.764 22579 22601 I AdrenoGLES-0: Reconstruct Branch               : NOTHING
04-23 10:42:55.764 22579 22601 I AdrenoGLES-0: Build Config                     : S P 8.0.11 AArch64
04-23 10:42:55.764 22579 22601 I AdrenoGLES-0: Driver Path                      : /vendor/lib64/egl/libGLESv2_adreno.so
04-23 10:42:55.772 22579 22601 I AdrenoGLES-0: PFP: 0x016ee183, ME: 0x00000000
04-23 10:42:55.868 22579 22579 I AssistStructure: Flattened final assist data: 2208 bytes, containing 1 windows, 12 views
04-23 10:43:03.863 22579 22594 W System  : A resource failed to call release. 
04-23 10:43:03.865 22579 22594 I chatty  : uid=10294(com.beemdevelopment.aegis) FinalizerDaemon identical 10 lines
04-23 10:43:03.865 22579 22594 W System  : A resource failed to call release. 
04-23 10:43:49.494 22579 22579 I AssistStructure: Flattened final assist data: 2208 bytes, containing 1 windows, 12 views
04-23 10:43:55.434 22579 22594 W System  : A resource failed to call release. 
04-23 10:43:55.435 22579 22594 I chatty  : uid=10294(com.beemdevelopment.aegis) FinalizerDaemon identical 12 lines
04-23 10:43:55.506 22579 22594 W System  : A resource failed to call release. 
04-23 10:43:59.646 22579 22579 W ListPreference: Setting a summary with a String formatting marker is no longer supported. You should use a SummaryProvider instead.
04-23 10:43:59.679 22579 22579 W ListPreference: Setting a summary with a String formatting marker is no longer supported. You should use a SummaryProvider instead.
04-23 10:43:59.889 22579 22601 D OpenGLRenderer: endAllActiveAnimators on 0x7b21e68090 (MenuPopupWindow$MenuDropDownListView) with handle 0x7a31de6f20
04-23 10:45:18.895 22579 22579 W System.err: com.beemdevelopment.aegis.crypto.KeyStoreHandleException: java.security.InvalidAlgorithmParameterException: java.lang.IllegalArgumentException: Int tag value out of range: -1
04-23 10:45:18.897 22579 22579 W System.err: 	at com.beemdevelopment.aegis.crypto.KeyStoreHandle.generateKey(KeyStoreHandle.java:65)
04-23 10:45:18.897 22579 22579 W System.err: 	at com.beemdevelopment.aegis.helpers.BiometricSlotInitializer.authenticate(BiometricSlotInitializer.java:63)
04-23 10:45:18.897 22579 22579 W System.err: 	at com.beemdevelopment.aegis.ui.PreferencesFragment$10.onPreferenceChange(PreferencesFragment.java:311)
04-23 10:45:18.897 22579 22579 W System.err: 	at androidx.preference.Preference.callChangeListener(Preference.java:1118)
04-23 10:45:18.897 22579 22579 W System.err: 	at androidx.preference.TwoStatePreference.onClick(TwoStatePreference.java:67)
04-23 10:45:18.897 22579 22579 W System.err: 	at androidx.preference.Preference.performClick(Preference.java:1182)
04-23 10:45:18.897 22579 22579 W System.err: 	at androidx.preference.Preference.performClick(Preference.java:1166)
04-23 10:45:18.897 22579 22579 W System.err: 	at androidx.preference.SwitchPreferenceCompat.performClick(SwitchPreferenceCompat.java:193)
04-23 10:45:18.897 22579 22579 W System.err: 	at androidx.preference.Preference$1.onClick(Preference.java:181)
04-23 10:45:18.897 22579 22579 W System.err: 	at android.view.View.performClick(View.java:7350)
04-23 10:45:18.897 22579 22579 W System.err: 	at android.view.View.performClickInternal(View.java:7327)
04-23 10:45:18.897 22579 22579 W System.err: 	at android.view.View.access$3600(View.java:807)
04-23 10:45:18.897 22579 22579 W System.err: 	at android.view.View$PerformClick.run(View.java:28166)
04-23 10:45:18.897 22579 22579 W System.err: 	at android.os.Handler.handleCallback(Handler.java:907)
	at android.os.Handler.handleCallback(Handler.java:907)
04-23 10:45:18.897 22579 22579 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Handler.handleCallback(Handler.java:907)
04-23 10:45:18.897 22579 22579 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:99)
04-23 10:45:18.897 22579 22579 W System.err: 	at android.os.Looper.loop(Looper.java:216)
	at android.os.Handler.handleCallback(Handler.java:907)
04-23 10:45:18.897 22579 22579 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:99)
04-23 10:45:18.897 22579 22579 W System.err: 	at android.os.Looper.loop(Looper.java:216)
04-23 10:45:18.897 22579 22579 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:7464)
	at android.os.Handler.handleCallback(Handler.java:907)
04-23 10:45:18.897 22579 22579 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:99)
04-23 10:45:18.897 22579 22579 W System.err: 	at android.os.Looper.loop(Looper.java:216)
04-23 10:45:18.897 22579 22579 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:7464)
04-23 10:45:18.897 22579 22579 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
04-23 10:45:18.897 22579 22579 W System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:549)
04-23 10:45:18.897 22579 22579 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:955)
	at android.os.Handler.handleCallback(Handler.java:907)
04-23 10:45:18.897 22579 22579 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:99)
04-23 10:45:18.897 22579 22579 W System.err: 	at android.os.Looper.loop(Looper.java:216)
04-23 10:45:18.897 22579 22579 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:7464)
04-23 10:45:18.897 22579 22579 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
04-23 10:45:18.897 22579 22579 W System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:549)
04-23 10:45:18.897 22579 22579 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:955)
04-23 10:45:18.897 22579 22579 W System.err: Caused by: java.security.InvalidAlgorithmParameterException: java.lang.IllegalArgumentException: Int tag value out of range: -1
	at android.os.Handler.handleCallback(Handler.java:907)
04-23 10:45:18.897 22579 22579 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:99)
04-23 10:45:18.897 22579 22579 W System.err: 	at android.os.Looper.loop(Looper.java:216)
04-23 10:45:18.897 22579 22579 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:7464)
04-23 10:45:18.897 22579 22579 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
04-23 10:45:18.897 22579 22579 W System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:549)
04-23 10:45:18.897 22579 22579 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:955)
04-23 10:45:18.897 22579 22579 W System.err: Caused by: java.security.InvalidAlgorithmParameterException: java.lang.IllegalArgumentException: Int tag value out of range: -1
04-23 10:45:18.897 22579 22579 W System.err: 	at android.security.keystore.AndroidKeyStoreKeyGeneratorSpi.engineInit(AndroidKeyStoreKeyGeneratorSpi.java:252)
	at android.os.Handler.handleCallback(Handler.java:907)
04-23 10:45:18.897 22579 22579 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:99)
04-23 10:45:18.897 22579 22579 W System.err: 	at android.os.Looper.loop(Looper.java:216)
04-23 10:45:18.897 22579 22579 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:7464)
04-23 10:45:18.897 22579 22579 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
04-23 10:45:18.897 22579 22579 W System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:549)
04-23 10:45:18.897 22579 22579 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:955)
04-23 10:45:18.897 22579 22579 W System.err: Caused by: java.security.InvalidAlgorithmParameterException: java.lang.IllegalArgumentException: Int tag value out of range: -1
04-23 10:45:18.897 22579 22579 W System.err: 	at android.security.keystore.AndroidKeyStoreKeyGeneratorSpi.engineInit(AndroidKeyStoreKeyGeneratorSpi.java:252)
04-23 10:45:18.897 22579 22579 W System.err: 	at android.security.keystore.AndroidKeyStoreKeyGeneratorSpi$AES.engineInit(AndroidKeyStoreKeyGeneratorSpi.java:53)
	at android.os.Handler.handleCallback(Handler.java:907)
04-23 10:45:18.897 22579 22579 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:99)
04-23 10:45:18.897 22579 22579 W System.err: 	at android.os.Looper.loop(Looper.java:216)
04-23 10:45:18.897 22579 22579 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:7464)
04-23 10:45:18.897 22579 22579 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
04-23 10:45:18.897 22579 22579 W System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:549)
04-23 10:45:18.897 22579 22579 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:955)
04-23 10:45:18.897 22579 22579 W System.err: Caused by: java.security.InvalidAlgorithmParameterException: java.lang.IllegalArgumentException: Int tag value out of range: -1
04-23 10:45:18.897 22579 22579 W System.err: 	at android.security.keystore.AndroidKeyStoreKeyGeneratorSpi.engineInit(AndroidKeyStoreKeyGeneratorSpi.java:252)
04-23 10:45:18.897 22579 22579 W System.err: 	at android.security.keystore.AndroidKeyStoreKeyGeneratorSpi$AES.engineInit(AndroidKeyStoreKeyGeneratorSpi.java:53)
04-23 10:45:18.897 22579 22579 W System.err: 	at javax.crypto.KeyGenerator.init(KeyGenerator.java:519)
	at android.os.Handler.handleCallback(Handler.java:907)
04-23 10:45:18.897 22579 22579 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:99)
04-23 10:45:18.897 22579 22579 W System.err: 	at android.os.Looper.loop(Looper.java:216)
04-23 10:45:18.897 22579 22579 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:7464)
04-23 10:45:18.897 22579 22579 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
04-23 10:45:18.897 22579 22579 W System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:549)
04-23 10:45:18.897 22579 22579 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:955)
04-23 10:45:18.897 22579 22579 W System.err: Caused by: java.security.InvalidAlgorithmParameterException: java.lang.IllegalArgumentException: Int tag value out of range: -1
04-23 10:45:18.897 22579 22579 W System.err: 	at android.security.keystore.AndroidKeyStoreKeyGeneratorSpi.engineInit(AndroidKeyStoreKeyGeneratorSpi.java:252)
04-23 10:45:18.897 22579 22579 W System.err: 	at android.security.keystore.AndroidKeyStoreKeyGeneratorSpi$AES.engineInit(AndroidKeyStoreKeyGeneratorSpi.java:53)
04-23 10:45:18.897 22579 22579 W System.err: 	at javax.crypto.KeyGenerator.init(KeyGenerator.java:519)
04-23 10:45:18.897 22579 22579 W System.err: 	at javax.crypto.KeyGenerator.init(KeyGenerator.java:502)
04-23 10:45:18.897 22579 22579 W System.err: 	at com.beemdevelopment.aegis.crypto.KeyStoreHandle.generateKey(KeyStoreHandle.java:54)
04-23 10:45:18.897 22579 22579 W System.err: 	... 19 more
04-23 10:45:18.897 22579 22579 W System.err: Caused by: java.lang.IllegalArgumentException: Int tag value out of range: -1
04-23 10:45:18.897 22579 22579 W System.err: 	at android.security.keymaster.KeymasterArguments.addUnsignedInt(KeymasterArguments.java:152)
04-23 10:45:18.897 22579 22579 W System.err: 	at android.security.keystore.KeymasterUtils.addUserAuthArgs(KeymasterUtils.java:170)
04-23 10:45:18.897 22579 22579 W System.err: 	at android.security.keystore.AndroidKeyStoreKeyGeneratorSpi.engineInit(AndroidKeyStoreKeyGeneratorSpi.java:250)
04-23 10:45:18.898 22579 22579 W System.err: 	... 23 more

```

**Comment by alexbakker** [comment]
Thanks for the report. We haven't seen this exception before, so this might be a bug in the developer preview. I'll see if I can reproduce this in an emulator.

**Comment by alexbakker** [comment]
Interesting! I can reproduce this an emulator. This appears to be a known issue: https://issuetracker.google.com/issues/151969454. It is marked as fixed, so my guess would be that the fix will be available in the next Developer Preview.

**Comment by squabbi** [comment]
Thanks for finding that issue! It has indeed been fixed in DP3! 👍
