### ISSUE TITLE
Can't export Aegis data

### ISSUE THREAD

**Issue by 4rnoP** [beemdevelopment/Aegis#577]
* __Version__: 1.3
* __Source__: F-Droid
* __Vault encrypted:__ Yes (with biometric unlock)
* __Device:__ OnePlus3T
* __Android version and ROM:__ crDroid 6.9 (Android 10)

While trying to export Aegis data, the app is crashing (with or without the option "Keep the vault encrypted").
I looked at similars issues and found [issue #491 ](https://github.com/beemdevelopment/Aegis/issues/491) but com.android.documentsui is installed, so that doesn't seems to be the problem.
I don't know if it's related, but the app never asked for files access permission, and  I can't manually allow it in the permission's settings for Aegis

###### Log
Log coming from the "Aegis keeps stopping", I have a button "Copy crash log URL" (I guess it's a crDroid feature).
```
time: 1598020571693
msg: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.CREATE_DOCUMENT cat=[android.intent.category.OPENABLE] typ=application/json (has extras) }
stacktrace: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.CREATE_DOCUMENT cat=[android.intent.category.OPENABLE] typ=application/json (has extras) }
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2064)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1718)
	at android.app.Activity.startActivityForResult(Activity.java:5210)
	at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:6)
	at androidx.core.app.ActivityCompat.startActivityForResult(ActivityCompat.java:1)
	at androidx.fragment.app.Fragment.startActivityForResult(Fragment.java:8)
	at com.beemdevelopment.aegis.ui.PreferencesFragment.lambda$startExport$16$PreferencesFragment(PreferencesFragment.java:7)
	at com.beemdevelopment.aegis.ui.-$$Lambda$PreferencesFragment$VzIxvx-hInpaG7EtVsaWHnxcy7A.onClick(Unknown Source:4)
	at androidx.appcompat.app.AlertController$ButtonHandler.handleMessage(AlertController.java:3)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940
```

**Comment by 4rnoP** [comment]
Indeed, after some search I reinstalled DocumentsUI on my phone and now it's fine.
Thank you a lot, and sorry to have taken your time.
