### ISSUE TITLE
crash when trying to export

### ISSUE THREAD

**Issue by jsmoment** [beemdevelopment/Aegis#622]
###### Info

* __Version__: 1.3.39
* __Source__: Google Play
* __Vault encrypted:__ Yes (with biometric unlock)
* __Device:__ Redmi Note 8T
* __Android version and ROM:__ Android 10, Havoc OS 3.9

###### Steps to reproduce

A detailed list of reproduction steps.
1. Decrypt the database.
2. Go to settings.
3. Try to export.
###### What do you expect to happen?
The app should let me export the database.
...

###### What happens instead?
The app crashes.
...

###### Log

```
If applicable, paste the debug log here.
```
time: 1606695071608
msg: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.CREATE_DOCUMENT cat=[android.intent.category.OPENABLE] typ=application/json (has extras) }
stacktrace: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.CREATE_DOCUMENT cat=[android.intent.category.OPENABLE] typ=application/json (has extras) }
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2064)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1718)
	at android.app.Activity.startActivityForResult(Activity.java:5210)
	at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:6)
	at androidx.core.app.ActivityCompat.startActivityForResult(ActivityCompat.java:1)
	at androidx.fragment.app.Fragment.startActivityForResult(Fragment.java:8)
	at com.beemdevelopment.aegis.ui.PreferencesFragment.lambda$startExport$16$PreferencesFragment(PreferencesFragment.java:7)
	at com.beemdevelopment.aegis.ui.-$$Lambda$PreferencesFragment$VzIxvx-hInpaG7EtVsaWHnxcy7A.onClick(Unknown Source:4)
	at androidx.appcompat.app.AlertController$ButtonHandler.handleMessage(AlertController.java:3)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:925)

**Comment by alexbakker** [comment]
Please check the existing tickets about this issue: https://github.com/beemdevelopment/Aegis/search?q=ActivityNotFoundException&type=issues. DocumentsUI is somehow missing from your device and you need to find a way to get it back.

**Comment by jsmoment** [comment]
> Please check the existing tickets about this issue: https://github.com/beemdevelopment/Aegis/search?q=ActivityNotFoundException&type=issues. DocumentsUI is somehow missing from your device and you need to find a way to get it back.

Thank you, I removed DocumentsUI when debloating my phone because I didn't know it's something important. I reinstalled it and it works.

**Comment by alexbakker** [comment]
Glad it works now! Could you let the author of the debloating guide you followed know that he's telling people to remove an essential system component from their phone?

**Comment by jsmoment** [comment]
> Glad it works now! Could you let the author of the debloating guide you followed know that he's telling people to remove an essential system component from their phone?

I just used a magisk module (Debloater) to remove system apps I didn't need.
