### ISSUE TITLE
Crash when i try to export or bakcup

### ISSUE THREAD

**Issue by rimko** [beemdevelopment/Aegis#679]
### Infos :
- Device : Redmi K 20 / Xiaomi Mi9-T
- OS : Android 10, LineageOS 17.1
- Version: 1.4.1
- Source: F-Droid
- Vault encrypted: Yes

### Issue :

When i try to export or backup, Aegis crash.
I have try downgrade to a previous version of Aegis on F-Droid but the installation fail.

### Log :

[debug.log](https://github.com/beemdevelopment/Aegis/files/5899479/debug.log)
`❯ adb logcat --pid=$(adb shell pidof -s com.beemdevelopment.aegis) > debug.log
❯ cat ./debug.log
--------- beginning of main
01-31 10:42:57.590 11531 11531 W ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@a811689
01-31 10:42:57.634 11531 11531 W ListPreference: Setting a summary with a String formatting marker is no longer supported. You should use a SummaryProvider instead.
01-31 10:42:57.662 11531 11531 W ListPreference: Setting a summary with a String formatting marker is no longer supported. You should use a SummaryProvider instead.
01-31 10:43:01.830 11531 11553 D OpenGLRenderer: endAllActiveAnimators on 0x7c9019a400 (RippleDrawable) with handle 0x7c90041e60
01-31 10:43:01.838 11531 11531 D AndroidRuntime: Shutting down VM
--------- beginning of crash
01-31 10:43:01.839 11531 11531 E AndroidRuntime: FATAL EXCEPTION: main
01-31 10:43:01.839 11531 11531 E AndroidRuntime: Process: com.beemdevelopment.aegis, PID: 11531
01-31 10:43:01.839 11531 11531 E AndroidRuntime: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.CREATE_DOCUMENT cat=[android.intent.category.OPENABLE] typ=application/json (has extras) }
01-31 10:43:01.839 11531 11531 E AndroidRuntime: 	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2058)
01-31 10:43:01.839 11531 11531 E AndroidRuntime: 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1716)
01-31 10:43:01.839 11531 11531 E AndroidRuntime: 	at android.app.Activity.startActivityForResult(Activity.java:5210)
01-31 10:43:01.839 11531 11531 E AndroidRuntime: 	at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:6)
01-31 10:43:01.839 11531 11531 E AndroidRuntime: 	at androidx.core.app.ActivityCompat.startActivityForResult(ActivityCompat.java:1)
01-31 10:43:01.839 11531 11531 E AndroidRuntime: 	at androidx.fragment.app.FragmentActivity$HostCallbacks.onStartActivityFromFragment(FragmentActivity.java:6)
01-31 10:43:01.839 11531 11531 E AndroidRuntime: 	at androidx.fragment.app.Fragment.startActivityForResult(Fragment.java:2)
01-31 10:43:01.839 11531 11531 E AndroidRuntime: 	at com.beemdevelopment.aegis.ui.PreferencesFragment.lambda$null$20$PreferencesFragment(PreferencesFragment.java:11)
01-31 10:43:01.839 11531 11531 E AndroidRuntime: 	at com.beemdevelopment.aegis.ui.-$$Lambda$PreferencesFragment$0m-umsnl5RSrmxyDzFDgcZSiD-M.onClick(Unknown Source:11)
01-31 10:43:01.839 11531 11531 E AndroidRuntime: 	at android.view.View.performClick(View.java:7259)
01-31 10:43:01.839 11531 11531 E AndroidRuntime: 	at android.view.View.performClickInternal(View.java:7236)
01-31 10:43:01.839 11531 11531 E AndroidRuntime: 	at android.view.View.access$3600(View.java:801)
01-31 10:43:01.839 11531 11531 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:27892)
01-31 10:43:01.839 11531 11531 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:883)
01-31 10:43:01.839 11531 11531 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:100)
01-31 10:43:01.839 11531 11531 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
01-31 10:43:01.839 11531 11531 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7356)
01-31 10:43:01.839 11531 11531 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-31 10:43:01.839 11531 11531 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
01-31 10:43:01.839 11531 11531 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
01-31 10:43:01.867 11531 11531 I Process : Sending signal. PID: 11531 SIG: 9
`

**Comment by alexbakker** [comment]
DocumentsUI is missing from your device. Did you "debloat" it? Please refer to the existing tickets about this issue: https://github.com/beemdevelopment/Aegis/search?q=android.intent.action.CREATE_DOCUMENT&type=issues.
