### ISSUE TITLE
App crashes when trying to import from Authenticator plus

### ISSUE THREAD

**Issue by THX-IOII** [beemdevelopment/Aegis#708]
Title says it all, asks for file then file password, if password is correct app closes and reopens back to login screen

**Comment by alexbakker** [comment]
See #670. Can you try disabling "Don't keep activities" in Developer options and report back if that fixes the issue?

**Comment by THX-IOII** [comment]
'Don't keep activities' was already disabled, if I enable it, it crashes
before asking for the password instead.

**Comment by alexbakker** [comment]
I see, please fill out the bug report template and [capture a log of the crash with ADB](https://github.com/beemdevelopment/Aegis/blob/master/CONTRIBUTING.md#capturing-a-log-with-adb).

**Comment by THX-IOII** [comment]
Here you go buddy

**Comment by alexbakker** [comment]
I don't see a filled out bug report template or a log file.

**Comment by THX-IOII** [comment]
Ah maybe github doesn't support attachments:

--------- beginning of system
03-19 09:22:56.073 19629 19629 I Timeline: Timeline: Activity_idle id:
***@***.*** time:98057121
03-19 09:22:56.144 19629 19629 W Editor  : updateCursorsPositions() :
layout = hintLayout
03-19 09:22:56.205 19629 19629 W Editor  : updateCursorsPositions() :
layout = hintLayout
03-19 09:23:06.379 19629 19629 I ViewRootImpl: ViewRoot's Touch Event :
ACTION_DOWN
03-19 09:23:06.443 19629 19629 I ViewRootImpl: ViewRoot's Touch Event :
ACTION_UP
03-19 09:23:06.489 19629 19629 D PhoneWindow: windowLightStatusBar : true,
enable View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR
03-19 09:23:06.528 19629 19629 I TouchFilterInputStageHelper:
[needTouchEventFilter] Displayid : 0
03-19 09:23:06.530 19629 19629 D BezellessGripSuppressionFilter:
getdisplaysize, x : 1440 y : 2880
03-19 09:23:06.580 19629 19629 D Editor  : hideClipTrayIfNeeded() TextView
is focused!! hideClipTray()
03-19 09:23:06.990 19629 19629 W ActivityThread: handleWindowVisibility: no
activity for token ***@***.***
03-19 09:23:07.042 19629 19629 D PhoneWindow: windowLightStatusBar : false,
disable View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR
03-19 09:23:07.125 19629 19629 I TouchFilterInputStageHelper:
[needTouchEventFilter] Displayid : 0
03-19 09:23:07.128 19629 19629 D BezellessGripSuppressionFilter:
getdisplaysize, x : 1440 y : 2880
03-19 09:23:07.129 19629 19629 D Editor  : hideClipTrayIfNeeded() TextView
is focused!! hideClipTray()
03-19 09:23:07.225 19629 19629 I Timeline: Timeline: Activity_idle id:
***@***.*** time:98068273
03-19 09:23:07.670 19629 19629 D Editor  : hideClipTrayIfNeeded() TextView
is focused!! hideClipTray()
03-19 09:23:11.118 19629 19629 I ViewRootImpl: ViewRoot's Touch Event :
ACTION_DOWN
03-19 09:23:11.210 19629 19629 I ViewRootImpl: ViewRoot's Touch Event :
ACTION_UP
03-19 09:23:11.263 19629 19629 I TouchFilterInputStageHelper:
[needTouchEventFilter] Displayid : 0
03-19 09:23:11.265 19629 19629 D BezellessGripSuppressionFilter:
getdisplaysize, x : 1440 y : 2880
03-19 09:23:12.125 19629 19629 I ViewRootImpl: ViewRoot's Touch Event :
ACTION_DOWN
03-19 09:23:12.195 19629 19629 I ViewRootImpl: ViewRoot's Touch Event :
ACTION_UP
03-19 09:23:12.344 19629 19629 W ActivityThread: handleWindowVisibility: no
activity for token ***@***.***
03-19 09:23:12.363 19629 19629 D PhoneWindow: windowLightStatusBar : false,
disable View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR
03-19 09:23:12.429 19629 19629 I TouchFilterInputStageHelper:
[needTouchEventFilter] Displayid : 0
03-19 09:23:12.429 19629 19629 D BezellessGripSuppressionFilter:
getdisplaysize, x : 1440 y : 2880
03-19 09:23:12.458 19629 19629 W ListPreference: Setting a summary with a
String formatting marker is no longer supported. You should use a
SummaryProvider instead.
03-19 09:23:12.511 19629 19629 W ListPreference: Setting a summary with a
String formatting marker is no longer supported. You should use a
SummaryProvider instead.
03-19 09:23:12.554 19629 19629 I Timeline: Timeline: Activity_idle id:
***@***.*** time:98073602
03-19 09:23:13.447 19629 19629 I ViewRootImpl: ViewRoot's Touch Event :
ACTION_DOWN
03-19 09:23:13.587 19629 19629 I ViewRootImpl: ViewRoot's Touch Event :
ACTION_UP
03-19 09:23:14.627 19629 19629 I ViewRootImpl: ViewRoot's Touch Event :
ACTION_DOWN
03-19 09:23:14.701 19629 19629 I ViewRootImpl: ViewRoot's Touch Event :
ACTION_UP
03-19 09:23:14.730 19629 19629 D PhoneWindow: windowLightStatusBar : false,
disable View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR
03-19 09:23:14.768 19629 19629 I TouchFilterInputStageHelper:
[needTouchEventFilter] Displayid : 0
03-19 09:23:14.768 19629 19629 D BezellessGripSuppressionFilter:
getdisplaysize, x : 1440 y : 2880
03-19 09:23:16.266 19629 19629 I ViewRootImpl: ViewRoot's Touch Event :
ACTION_DOWN
03-19 09:23:16.352 19629 19629 I ViewRootImpl: ViewRoot's Touch Event :
ACTION_UP
03-19 09:23:17.370 19629 19629 I ViewRootImpl: ViewRoot's Touch Event :
ACTION_DOWN
03-19 09:23:17.451 19629 19629 I ViewRootImpl: ViewRoot's Touch Event :
ACTION_UP
03-19 09:23:17.500 19629 19648 D OpenGLRenderer: endAllActiveAnimators on
0x6f32db6800 (RippleDrawable) with handle 0x6f32bad4a0
03-19 09:23:19.673 19629 19629 D PhoneWindow: windowLightStatusBar : false,
disable View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR
03-19 09:23:19.690 19629 19629 I TouchFilterInputStageHelper:
[needTouchEventFilter] Displayid : 0
03-19 09:23:19.691 19629 19629 D BezellessGripSuppressionFilter:
getdisplaysize, x : 1440 y : 2880
03-19 09:23:19.740 19629 19629 D Editor  : setInputTypeforClipTray(): 0
03-19 09:23:19.759 19629 19629 W Editor  : updateCursorsPositions() :
layout = hintLayout
03-19 09:23:19.824 19629 19629 I Timeline: Timeline: Activity_idle id:
***@***.*** time:98080872
03-19 09:23:20.749 19629 19629 W Editor  : updateCursorsPositions() :
layout = hintLayout
03-19 09:23:26.932 19629 19629 I ViewRootImpl: ViewRoot's Touch Event :
ACTION_DOWN
03-19 09:23:26.991 19629 19629 I ViewRootImpl: ViewRoot's Touch Event :
ACTION_UP
03-19 09:23:27.156 19629 19629 D AndroidRuntime: Shutting down VM
--------- beginning of crash
03-19 09:23:27.157 19629 19629 E AndroidRuntime: FATAL EXCEPTION: main
03-19 09:23:27.157 19629 19629 E AndroidRuntime: Process:
com.beemdevelopment.aegis, PID: 19629
03-19 09:23:27.157 19629 19629 E AndroidRuntime:
java.lang.RuntimeException: Parcelable encountered IOException writing
serializable object (name =
com.beemdevelopment.aegis.importers.DatabaseImporterEntryException)
03-19 09:23:27.157 19629 19629 E AndroidRuntime: at
android.os.Parcel.writeSerializable(Parcel.java:1714)
03-19 09:23:27.157 19629 19629 E AndroidRuntime: at
android.os.Parcel.writeValue(Parcel.java:1662)
03-19 09:23:27.157 19629 19629 E AndroidRuntime: at
android.os.Parcel.writeList(Parcel.java:963)
03-19 09:23:27.157 19629 19629 E AndroidRuntime: at
android.os.Parcel.writeValue(Parcel.java:1611)
03-19 09:23:27.157 19629 19629 E AndroidRuntime: at
android.os.Parcel.writeArrayMapInternal(Parcel.java:875)
03-19 09:23:27.157 19629 19629 E AndroidRuntime: at
android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1579)
03-19 09:23:27.157 19629 19629 E AndroidRuntime: at
android.os.Bundle.writeToParcel(Bundle.java:1233)
03-19 09:23:27.157 19629 19629 E AndroidRuntime: at
android.os.Parcel.writeBundle(Parcel.java:915)
03-19 09:23:27.157 19629 19629 E AndroidRuntime: at
android.content.Intent.writeToParcel(Intent.java:9980)
03-19 09:23:27.157 19629 19629 E AndroidRuntime: at
android.app.IActivityManager$Stub$Proxy.startActivity(IActivityManager.java:3609)
03-19 09:23:27.157 19629 19629 E AndroidRuntime: at
android.app.Instrumentation.execStartActivity(Instrumentation.java:1671)
03-19 09:23:27.157 19629 19629 E AndroidRuntime: at
android.app.Activity.startActivityForResult(Activity.java:4602)
03-19 09:23:27.157 19629 19629 E AndroidRuntime: at
androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:6)
03-19 09:23:27.157 19629 19629 E AndroidRuntime: at
com.beemdevelopment.aegis.ui.AegisActivity.startActivityForResult(AegisActivity.java:7)
03-19 09:23:27.157 19629 19629 E AndroidRuntime: at
androidx.core.app.ActivityCompat.startActivityForResult(ActivityCompat.java:1)
03-19 09:23:27.157 19629 19629 E AndroidRuntime: at
androidx.fragment.app.FragmentActivity$HostCallbacks.onStartActivityFromFragment(FragmentActivity.java:6)
03-19 09:23:27.157 19629 19629 E AndroidRuntime: at
androidx.fragment.app.Fragment.startActivityForResult(Fragment.java:2)
03-19 09:23:27.157 19629 19629 E AndroidRuntime: at
com.beemdevelopment.aegis.ui.PreferencesFragment.importDatabase(PreferencesFragment.java:10)
03-19 09:23:27.157 19629 19629 E AndroidRuntime: at
com.beemdevelopment.aegis.ui.PreferencesFragment.access$1100(PreferencesFragment.java:1)
03-19 09:23:27.157 19629 19629 E AndroidRuntime: at
com.beemdevelopment.aegis.ui.PreferencesFragment$13.onStateDecrypted(PreferencesFragment.java:1)
03-19 09:23:27.157 19629 19629 E AndroidRuntime: at
com.beemdevelopment.aegis.importers.AuthenticatorPlusImporter$EncryptedState.lambda$decrypt$0$AuthenticatorPlusImporter$EncryptedState(AuthenticatorPlusImporter.java:10)
03-19 09:23:27.157 19629 19629 E AndroidRuntime: at
com.beemdevelopment.aegis.importers.-$$Lambda$AuthenticatorPlusImporter$EncryptedState$LqFUCS2MUSmSon_3pAFX5icccbE.onTextInputResult(Unknown
Source:6)
03-19 09:23:27.157 19629 19629 E AndroidRuntime: at
androidx.appcompat.app.AppCompatDelegateImpl$ConfigurationImplApi17.lambda$showTextInputDialog$4(AppCompatDelegateImpl.java:2)
03-19 09:23:27.157 19629 19629 E AndroidRuntime: at
androidx.appcompat.app.-$$Lambda$AppCompatDelegateImpl$ConfigurationImplApi17$swlzO9qH8cKZ0YyfbUnBYvapiUs.onClick(Unknown
Source:4)
03-19 09:23:27.157 19629 19629 E AndroidRuntime: at
androidx.appcompat.app.AlertController$ButtonHandler.handleMessage(AlertController.java:3)
03-19 09:23:27.157 19629 19629 E AndroidRuntime: at
android.os.Handler.dispatchMessage(Handler.java:106)
03-19 09:23:27.157 19629 19629 E AndroidRuntime: at
android.os.Looper.loop(Looper.java:205)
03-19 09:23:27.157 19629 19629 E AndroidRuntime: at
android.app.ActivityThread.main(ActivityThread.java:6991)
03-19 09:23:27.157 19629 19629 E AndroidRuntime: at
java.lang.reflect.Method.invoke(Native Method)
03-19 09:23:27.157 19629 19629 E AndroidRuntime: at
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
03-19 09:23:27.157 19629 19629 E AndroidRuntime: at
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:884)
03-19 09:23:27.157 19629 19629 E AndroidRuntime: Caused by:
java.io.NotSerializableException: android.net.Uri$StringUri
03-19 09:23:27.157 19629 19629 E AndroidRuntime: at
java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1240)
03-19 09:23:27.157 19629 19629 E AndroidRuntime: at
java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1604)
03-19 09:23:27.157 19629 19629 E AndroidRuntime: at
java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1565)
03-19 09:23:27.157 19629 19629 E AndroidRuntime: at
java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1488)
03-19 09:23:27.157 19629 19629 E AndroidRuntime: at
java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1234)
03-19 09:23:27.157 19629 19629 E AndroidRuntime: at
java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1604)
03-19 09:23:27.157 19629 19629 E AndroidRuntime: at
java.io.ObjectOutputStream.defaultWriteObject(ObjectOutputStream.java:463)
03-19 09:23:27.157 19629 19629 E AndroidRuntime: at
java.lang.Throwable.writeObject(Throwable.java:977)
03-19 09:23:27.157 19629 19629 E AndroidRuntime: at
java.lang.reflect.Method.invoke(Native Method)
03-19 09:23:27.157 19629 19629 E AndroidRuntime: at
java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1037)
03-19 09:23:27.157 19629 19629 E AndroidRuntime: at
java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1552)
03-19 09:23:27.157 19629 19629 E AndroidRuntime: at
java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1488)
03-19 09:23:27.157 19629 19629 E AndroidRuntime: at
java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1234)
03-19 09:23:27.157 19629 19629 E AndroidRuntime: at
java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:354)
03-19 09:23:27.157 19629 19629 E AndroidRuntime: at
android.os.Parcel.writeSerializable(Parcel.java:1709)
03-19 09:23:27.157 19629 19629 E AndroidRuntime: ... 30 more
03-19 09:23:27.189 19629 19629 I Process : Sending signal. PID: 19629 SIG: 9

**Comment by alexbakker** [comment]
Can you try the following debug APK and report whether you can still reproduce the issue with that: https://alexbakker.me/u/x47rfwgsg0.apk?

Better format of the log for those reading along: 

```
--------- beginning of system
03-19 09:22:56.073 19629 19629 I Timeline: Timeline: Activity_idle id: ***@***.*** time:98057121
03-19 09:22:56.144 19629 19629 W Editor  : updateCursorsPositions() : layout = hintLayout
03-19 09:22:56.205 19629 19629 W Editor  : updateCursorsPositions() : layout = hintLayout
03-19 09:23:06.379 19629 19629 I ViewRootImpl: ViewRoot's Touch Event : ACTION_DOWN
03-19 09:23:06.443 19629 19629 I ViewRootImpl: ViewRoot's Touch Event : ACTION_UP
03-19 09:23:06.489 19629 19629 D PhoneWindow: windowLightStatusBar : true, enable View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR
03-19 09:23:06.528 19629 19629 I TouchFilterInputStageHelper: [needTouchEventFilter] Displayid : 0
03-19 09:23:06.530 19629 19629 D BezellessGripSuppressionFilter: getdisplaysize, x : 1440 y : 2880
03-19 09:23:06.580 19629 19629 D Editor  : hideClipTrayIfNeeded() TextView is focused!! hideClipTray()
03-19 09:23:06.990 19629 19629 W ActivityThread: handleWindowVisibility: no activity for token ***@***.***
03-19 09:23:07.042 19629 19629 D PhoneWindow: windowLightStatusBar : false, disable View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR
03-19 09:23:07.125 19629 19629 I TouchFilterInputStageHelper: [needTouchEventFilter] Displayid : 0
03-19 09:23:07.128 19629 19629 D BezellessGripSuppressionFilter: getdisplaysize, x : 1440 y : 2880
03-19 09:23:07.129 19629 19629 D Editor  : hideClipTrayIfNeeded() TextView is focused!! hideClipTray()
03-19 09:23:07.225 19629 19629 I Timeline: Timeline: Activity_idle id: ***@***.*** time:98068273
03-19 09:23:07.670 19629 19629 D Editor  : hideClipTrayIfNeeded() TextView is focused!! hideClipTray()
03-19 09:23:11.118 19629 19629 I ViewRootImpl: ViewRoot's Touch Event : ACTION_DOWN
03-19 09:23:11.210 19629 19629 I ViewRootImpl: ViewRoot's Touch Event : ACTION_UP
03-19 09:23:11.263 19629 19629 I TouchFilterInputStageHelper: [needTouchEventFilter] Displayid : 0
03-19 09:23:11.265 19629 19629 D BezellessGripSuppressionFilter: getdisplaysize, x : 1440 y : 2880
03-19 09:23:12.125 19629 19629 I ViewRootImpl: ViewRoot's Touch Event : ACTION_DOWN
03-19 09:23:12.195 19629 19629 I ViewRootImpl: ViewRoot's Touch Event : ACTION_UP
03-19 09:23:12.344 19629 19629 W ActivityThread: handleWindowVisibility: no activity for token ***@***.***
03-19 09:23:12.363 19629 19629 D PhoneWindow: windowLightStatusBar : false, disable View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR
03-19 09:23:12.429 19629 19629 I TouchFilterInputStageHelper: [needTouchEventFilter] Displayid : 0
03-19 09:23:12.429 19629 19629 D BezellessGripSuppressionFilter: getdisplaysize, x : 1440 y : 2880
03-19 09:23:12.458 19629 19629 W ListPreference: Setting a summary with a String formatting marker is no longer supported. You should use a SummaryProvider instead.
03-19 09:23:12.511 19629 19629 W ListPreference: Setting a summary with a String formatting marker is no longer supported. You should use a SummaryProvider instead.
03-19 09:23:12.554 19629 19629 I Timeline: Timeline: Activity_idle id: ***@***.*** time:98073602
03-19 09:23:13.447 19629 19629 I ViewRootImpl: ViewRoot's Touch Event : ACTION_DOWN
03-19 09:23:13.587 19629 19629 I ViewRootImpl: ViewRoot's Touch Event : ACTION_UP
03-19 09:23:14.627 19629 19629 I ViewRootImpl: ViewRoot's Touch Event : ACTION_DOWN
03-19 09:23:14.701 19629 19629 I ViewRootImpl: ViewRoot's Touch Event : ACTION_UP
03-19 09:23:14.730 19629 19629 D PhoneWindow: windowLightStatusBar : false, disable View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR
03-19 09:23:14.768 19629 19629 I TouchFilterInputStageHelper: [needTouchEventFilter] Displayid : 0
03-19 09:23:14.768 19629 19629 D BezellessGripSuppressionFilter: getdisplaysize, x : 1440 y : 2880
03-19 09:23:16.266 19629 19629 I ViewRootImpl: ViewRoot's Touch Event : ACTION_DOWN
03-19 09:23:16.352 19629 19629 I ViewRootImpl: ViewRoot's Touch Event : ACTION_UP
03-19 09:23:17.370 19629 19629 I ViewRootImpl: ViewRoot's Touch Event : ACTION_DOWN
03-19 09:23:17.451 19629 19629 I ViewRootImpl: ViewRoot's Touch Event : ACTION_UP
03-19 09:23:17.500 19629 19648 D OpenGLRenderer: endAllActiveAnimators on 0x6f32db6800 (RippleDrawable) with handle 0x6f32bad4a0
03-19 09:23:19.673 19629 19629 D PhoneWindow: windowLightStatusBar : false, disable View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR
03-19 09:23:19.690 19629 19629 I TouchFilterInputStageHelper: [needTouchEventFilter] Displayid : 0
03-19 09:23:19.691 19629 19629 D BezellessGripSuppressionFilter: getdisplaysize, x : 1440 y : 2880
03-19 09:23:19.740 19629 19629 D Editor  : setInputTypeforClipTray(): 0
03-19 09:23:19.759 19629 19629 W Editor  : updateCursorsPositions() : layout = hintLayout
03-19 09:23:19.824 19629 19629 I Timeline: Timeline: Activity_idle id: ***@***.*** time:98080872
03-19 09:23:20.749 19629 19629 W Editor  : updateCursorsPositions() : layout = hintLayout
03-19 09:23:26.932 19629 19629 I ViewRootImpl: ViewRoot's Touch Event : ACTION_DOWN
03-19 09:23:26.991 19629 19629 I ViewRootImpl: ViewRoot's Touch Event : ACTION_UP
03-19 09:23:27.156 19629 19629 D AndroidRuntime: Shutting down VM
--------- beginning of crash
03-19 09:23:27.157 19629 19629 E AndroidRuntime: FATAL EXCEPTION: main
03-19 09:23:27.157 19629 19629 E AndroidRuntime: Process: com.beemdevelopment.aegis, PID: 19629
03-19 09:23:27.157 19629 19629 E AndroidRuntime: java.lang.RuntimeException: Parcelable encountered IOException writing serializable object (name = com.beemdevelopment.aegis.importers.DatabaseImporterEntryException)
03-19 09:23:27.157 19629 19629 E AndroidRuntime: at android.os.Parcel.writeSerializable(Parcel.java:1714)
03-19 09:23:27.157 19629 19629 E AndroidRuntime: at android.os.Parcel.writeValue(Parcel.java:1662)
03-19 09:23:27.157 19629 19629 E AndroidRuntime: at android.os.Parcel.writeList(Parcel.java:963)
03-19 09:23:27.157 19629 19629 E AndroidRuntime: at android.os.Parcel.writeValue(Parcel.java:1611)
03-19 09:23:27.157 19629 19629 E AndroidRuntime: at android.os.Parcel.writeArrayMapInternal(Parcel.java:875)
03-19 09:23:27.157 19629 19629 E AndroidRuntime: at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1579)
03-19 09:23:27.157 19629 19629 E AndroidRuntime: at android.os.Bundle.writeToParcel(Bundle.java:1233)
03-19 09:23:27.157 19629 19629 E AndroidRuntime: at android.os.Parcel.writeBundle(Parcel.java:915)
03-19 09:23:27.157 19629 19629 E AndroidRuntime: at android.content.Intent.writeToParcel(Intent.java:9980)
03-19 09:23:27.157 19629 19629 E AndroidRuntime: at android.app.IActivityManager$Stub$Proxy.startActivity(IActivityManager.java:3609)
03-19 09:23:27.157 19629 19629 E AndroidRuntime: at android.app.Instrumentation.execStartActivity(Instrumentation.java:1671)
03-19 09:23:27.157 19629 19629 E AndroidRuntime: at android.app.Activity.startActivityForResult(Activity.java:4602)
03-19 09:23:27.157 19629 19629 E AndroidRuntime: at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:6)
03-19 09:23:27.157 19629 19629 E AndroidRuntime: at com.beemdevelopment.aegis.ui.AegisActivity.startActivityForResult(AegisActivity.java:7)
03-19 09:23:27.157 19629 19629 E AndroidRuntime: at androidx.core.app.ActivityCompat.startActivityForResult(ActivityCompat.java:1)
03-19 09:23:27.157 19629 19629 E AndroidRuntime: at androidx.fragment.app.FragmentActivity$HostCallbacks.onStartActivityFromFragment(FragmentActivity.java:6)
03-19 09:23:27.157 19629 19629 E AndroidRuntime: at androidx.fragment.app.Fragment.startActivityForResult(Fragment.java:2)
03-19 09:23:27.157 19629 19629 E AndroidRuntime: at com.beemdevelopment.aegis.ui.PreferencesFragment.importDatabase(PreferencesFragment.java:10)
03-19 09:23:27.157 19629 19629 E AndroidRuntime: at com.beemdevelopment.aegis.ui.PreferencesFragment.access$1100(PreferencesFragment.java:1)
03-19 09:23:27.157 19629 19629 E AndroidRuntime: at com.beemdevelopment.aegis.ui.PreferencesFragment$13.onStateDecrypted(PreferencesFragment.java:1)
03-19 09:23:27.157 19629 19629 E AndroidRuntime: at com.beemdevelopment.aegis.importers.AuthenticatorPlusImporter$EncryptedState.lambda$decrypt$0$AuthenticatorPlusImporter$EncryptedState(AuthenticatorPlusImporter.java:10)
03-19 09:23:27.157 19629 19629 E AndroidRuntime: at com.beemdevelopment.aegis.importers.-$$Lambda$AuthenticatorPlusImporter$EncryptedState$LqFUCS2MUSmSon_3pAFX5icccbE.onTextInputResult(Unknown Source:6)
03-19 09:23:27.157 19629 19629 E AndroidRuntime: at androidx.appcompat.app.AppCompatDelegateImpl$ConfigurationImplApi17.lambda$showTextInputDialog$4(AppCompatDelegateImpl.java:2)
03-19 09:23:27.157 19629 19629 E AndroidRuntime: at androidx.appcompat.app.-$$Lambda$AppCompatDelegateImpl$ConfigurationImplApi17$swlzO9qH8cKZ0YyfbUnBYvapiUs.onClick(Unknown Source:4)
03-19 09:23:27.157 19629 19629 E AndroidRuntime: at androidx.appcompat.app.AlertController$ButtonHandler.handleMessage(AlertController.java:3)
03-19 09:23:27.157 19629 19629 E AndroidRuntime: at android.os.Handler.dispatchMessage(Handler.java:106)
03-19 09:23:27.157 19629 19629 E AndroidRuntime: at android.os.Looper.loop(Looper.java:205)
03-19 09:23:27.157 19629 19629 E AndroidRuntime: at android.app.ActivityThread.main(ActivityThread.java:6991)
03-19 09:23:27.157 19629 19629 E AndroidRuntime: at java.lang.reflect.Method.invoke(Native Method)
03-19 09:23:27.157 19629 19629 E AndroidRuntime: at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
03-19 09:23:27.157 19629 19629 E AndroidRuntime: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:884)
03-19 09:23:27.157 19629 19629 E AndroidRuntime: Caused by: java.io.NotSerializableException: android.net.Uri$StringUri
03-19 09:23:27.157 19629 19629 E AndroidRuntime: at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1240)
03-19 09:23:27.157 19629 19629 E AndroidRuntime: at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1604)
03-19 09:23:27.157 19629 19629 E AndroidRuntime: at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1565)
03-19 09:23:27.157 19629 19629 E AndroidRuntime: at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1488)
03-19 09:23:27.157 19629 19629 E AndroidRuntime: at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1234)
03-19 09:23:27.157 19629 19629 E AndroidRuntime: at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1604)
03-19 09:23:27.157 19629 19629 E AndroidRuntime: at java.io.ObjectOutputStream.defaultWriteObject(ObjectOutputStream.java:463)
03-19 09:23:27.157 19629 19629 E AndroidRuntime: at java.lang.Throwable.writeObject(Throwable.java:977)
03-19 09:23:27.157 19629 19629 E AndroidRuntime: at java.lang.reflect.Method.invoke(Native Method)
03-19 09:23:27.157 19629 19629 E AndroidRuntime: at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1037)
03-19 09:23:27.157 19629 19629 E AndroidRuntime: at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1552)
03-19 09:23:27.157 19629 19629 E AndroidRuntime: at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1488)
03-19 09:23:27.157 19629 19629 E AndroidRuntime: at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1234)
03-19 09:23:27.157 19629 19629 E AndroidRuntime: at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:354)
03-19 09:23:27.157 19629 19629 E AndroidRuntime: at android.os.Parcel.writeSerializable(Parcel.java:1709)
03-19 09:23:27.157 19629 19629 E AndroidRuntime: ... 30 more
03-19 09:23:27.189 19629 19629 I Process : Sending signal. PID: 19629 SIG: 9
```

**Comment by THX-IOII** [comment]
Debug build was able to import almost everything correctly, except for one
entry which bugged out with:

com.beemdevelopment.aegis.otp.GoogleAuthInfoException: Bad secret
(java.lang.IllegalArgumentException:
com.google.common.io.BaseEncoding$DecodingException: Invalid input length
17)
