### ISSUE TITLE
Black screen when adding an entry by scanning QR code

### ISSUE THREAD

**Issue by markochk** [beemdevelopment/Aegis#76]
When adding an entry via QR code scan, app shows black screen instead of what the camera is seeing. I can see green edges, text at the top, button to switch cameras and red blinking horizontal line. App also feels laggy, as navigation buttons don't respond immediately. It sometimes opens the camera without an issue and doesn't lag, but that happens once every 15 attempts (or maybe even more than that).
Switching to front camera can sometimes make it work, but it's difficult to scan with it, and switching to back camera again shows black screen.

I'm running version 0.3.3 installed from F-Droid, and I'm using a Huawei Honor 6x with Android 9.0 (rooted, running a custom ROM).

**Comment by alexbakker** [comment]
That sounds odd. We don't really do anything advanced with the camera ourselves, so it could be an issue with the me.dm7.barcodescanner:zxing library we're using. I see that version 1.9 is pretty outdated, so I've made a debug build that contains a small change and uses version 1.9.8: [https:/alexbakker.me/u/krjcavvvjp.apk](https:/alexbakker.me/u/krjcavvvjp.apk) ([branch](https://github.com/alexbakker/Aegis/tree/camera-fix)). Can you check if that fixes the issue for you? Can you also provide a logcat? It looks like the library swallows and prints any exceptions that occur when opening the camera, so we might get some useful info from a log.

Also, since you're running a custom ROM, I'll ask the obvious question: do you have any issues with using your front facing camera in other apps?

**Comment by markochk** [comment]
Thanks for replying. Unfortunately, it doesn't fix the issue. I've attached a logcat, but this is the first time I've used it, so apologies if it's not perfect. I'm open to do more testing.

I haven't used it that way a lot, but I haven't had any issues. Prior to using this app, I had used andOTP and I've had no issues scanning with it. I also have Open camera and zxing QR code reader installed and they work properly.

[1.txt](https://github.com/beemdevelopment/Aegis/files/3135752/1.txt)

**Comment by alexbakker** [comment]
Thanks for the log. This appears to be the relevant bit:

```
[ 05-01 21:14:38.362  8045:13334 E/Camera   ]
Error 1

[ 05-01 21:14:38.684  8045: 8045 E/CameraPreview ]
java.lang.RuntimeException: startPreview failed
java.lang.RuntimeException: startPreview failed
	at android.hardware.Camera.startPreview(Native Method)
	at me.dm7.barcodescanner.core.CameraPreview.showCameraPreview(CameraPreview.java:91)
	at me.dm7.barcodescanner.core.CameraPreview.surfaceChanged(CameraPreview.java:73)
	at android.view.SurfaceView.updateSurface(SurfaceView.java:682)
	at android.view.SurfaceView.setFrame(SurfaceView.java:345)
	at android.view.View.layout(View.java:20673)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:20676)
	at android.view.ViewGroup.layout(ViewGroup.java:6194)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:20676)
	at android.view.ViewGroup.layout(ViewGroup.java:6194)
	at androidx.appcompat.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:444)
	at android.view.View.layout(View.java:20676)
	at android.view.ViewGroup.layout(ViewGroup.java:6194)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:20676)
	at android.view.ViewGroup.layout(ViewGroup.java:6194)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
	at android.view.View.layout(View.java:20676)
	at android.view.ViewGroup.layout(ViewGroup.java:6194)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:753)
	at android.view.View.layout(View.java:20676)
	at android.view.ViewGroup.layout(ViewGroup.java:6194)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2792)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2319)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1460)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7191)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
	at android.view.Choreographer.doCallbacks(Choreographer.java:761)
	at android.view.Choreographer.doFrame(Choreographer.java:696)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6680)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:495)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

The Camera API that the library uses is deprecated, but ZXing's barcode scanner also uses it, so that can't be the issue either. I made a new debug build where I removed all camera selection logic that we do: https://alexbakker.me/u/zanbmzv47y.apk. I'm out of ideas for now if that doesn't help.

**Comment by markochk** [comment]
Still doesn't work. It could be custom ROM's fault, as it has a few peculiarities.
I tried ZXing's barcode scanner, and it works every time.
It's not a big issue, I just have to be persistent until it opens the camera properly.

I've attached more logcat's if you're interested:
[1.txt](https://github.com/beemdevelopment/Aegis/files/3136919/1.txt)
[2.txt](https://github.com/beemdevelopment/Aegis/files/3136920/2.txt)
[3.txt](https://github.com/beemdevelopment/Aegis/files/3136921/3.txt)

Anyway, thanks for making this app and for your help.

**Comment by jyotirmayghosh** [comment]
@alexbakker 
I do have the same error when I am trying to preview the front camera. But it works fine with the rear camera.

If you find any solution, please update?
thanks

**Comment by alexbakker** [comment]
@jyotirmayghosh We can't really do much about this as we didn't write the camera handling code ourselves. We could try using a different library though. [zxing-android-embedded](https://github.com/journeyapps/zxing-android-embedded) seems to be better maintained than to one we're using currently.

We can also offer users the option to use the Barcode Scanner app if they're having issues. See: https://github.com/zxing/zxing/wiki/Scanning-Via-Intent.
