### ISSUE TITLE
Crash if trying to double-click on copy button

### ISSUE THREAD

**Issue by qwerty287** [beemdevelopment/Aegis#921]
###### Info

* __Version__: 2.0.3
* __Source__: F-Droid
* __Vault encrypted__: Yes (with biometric unlock)
* __Android version and ROM__: stock Android 11

###### Steps to reproduce

Try to double click the copy button after selecting an entry.

###### What do you expect to happen?

That nothing happens and the entry is un-selected as it happens if clicking once.

###### What happens instead?

This crash:

```
FATAL EXCEPTION: main
Process: com.beemdevelopment.aegis, PID: 31632
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.get(ArrayList.java:437)
	at com.beemdevelopment.aegis.ui.MainActivity$ActionModeCallbacks.onActionItemClicked(MainActivity.java:30)
	at androidx.appcompat.app.AppCompatDelegateImpl$ActionModeCallbackWrapperV9.onActionItemClicked(AppCompatDelegateImpl.java:1)
	at androidx.appcompat.view.StandaloneActionMode.onMenuItemSelected(StandaloneActionMode.java:1)
	at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:1)
	at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:5)
	at androidx.appcompat.widget.ActionMenuView.invokeItem(ActionMenuView.java:2)
	at androidx.appcompat.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:2)
	at android.view.View.performClick(View.java:7462)
	at android.view.View.performClickInternal(View.java:7426)
	at android.view.View.access$3600(View.java:811)
	at android.view.View$PerformClick.run(View.java:28323)
```

**Comment by alexbakker** [comment]
Thanks for the report. I'm able to reproduce this.
