### ISSUE TITLE
Crash from imported keys

### ISSUE THREAD

**Issue by modelmat** [beemdevelopment/Aegis#975]
###### Info

* __Version__: 2.0.3
* __Source__: (Google Play/GitHub/F-Droid/?) F-Droid
* __Vault encrypted__: Yes (with biometric unlock)
* __Device__: OPPO CPH1611
* __Android version and ROM__: 7.11, ColorOS V3.1

###### Steps to reproduce

Created a series of `otpauth://` from another app  for import (I no haz root :upside_down_face: ) in a plaintext keys.txt file.

One of them was typo'd with `otpauth://totp/<label>:?secret=`**&**`<key>`, e.g. `otpauth://totp/ZZZ:ZZZ?secret=&Secret=SHA1&digits=6&period=30` (reproduces for me).

App now crashes when trying to render the view. If the view renders, but only crashes when scrolling into view (i.e. the "start" view does not contain the bad entry), enabling "tap to reveal" allows me to see it and delete it.

###### What do you expect to happen?

Give malformed input error _when_ importing, not after.

###### What happens instead?

Crash after import, app in broken state and can't load.

###### Log

```
08-31 19:15:25.990  9702  9702 E AndroidRuntime: FATAL EXCEPTION: main
08-31 19:15:25.990  9702  9702 E AndroidRuntime: Process: com.beemdevelopment.aegis, PID: 9702
08-31 19:15:25.990  9702  9702 E AndroidRuntime: java.lang.IllegalArgumentException: Empty key
08-31 19:15:25.990  9702  9702 E AndroidRuntime: 	at javax.crypto.spec.SecretKeySpec.<init>(SecretKeySpec.java:96)
08-31 19:15:25.990  9702  9702 E AndroidRuntime: 	at androidx.preference.R$style.generateOTP(Unknown Source)
08-31 19:15:25.990  9702  9702 E AndroidRuntime: 	at com.beemdevelopment.aegis.crypto.otp.TOTP.generateOTP(TOTP.java:3)
08-31 19:15:25.990  9702  9702 E AndroidRuntime: 	at com.beemdevelopment.aegis.otp.TotpInfo.getOtp(TotpInfo.java:5)
08-31 19:15:25.990  9702  9702 E AndroidRuntime: 	at com.beemdevelopment.aegis.ui.views.EntryHolder.updateCode(EntryHolder.java:3)
08-31 19:15:25.990  9702  9702 E AndroidRuntime: 	at com.beemdevelopment.aegis.ui.views.EntryHolder.refreshCode(EntryHolder.java:2)
08-31 19:15:25.990  9702  9702 E AndroidRuntime: 	at com.beemdevelopment.aegis.ui.views.EntryAdapter.onBindViewHolder(EntryAdapter.java:32)
08-31 19:15:25.990  9702  9702 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:176)
08-31 19:15:25.990  9702  9702 E AndroidRuntime: 	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:9)
08-31 19:15:25.990  9702  9702 E AndroidRuntime: 	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1)
08-31 19:15:25.990  9702  9702 E AndroidRuntime: 	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:12)
08-31 19:15:25.990  9702  9702 E AndroidRuntime: 	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:119)
08-31 19:15:25.990  9702  9702 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:14)
08-31 19:15:25.990  9702  9702 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:15)
08-31 19:15:25.990  9702  9702 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:3)
08-31 19:15:25.990  9702  9702 E AndroidRuntime: 	at android.view.View.layout(View.java:17776)
08-31 19:15:25.990  9702  9702 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:5632)
08-31 19:15:25.990  9702  9702 E AndroidRuntime: 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
08-31 19:15:25.990  9702  9702 E AndroidRuntime: 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
08-31 19:15:25.990  9702  9702 E AndroidRuntime: 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
08-31 19:15:25.990  9702  9702 E AndroidRuntime: 	at android.view.View.layout(View.java:17776)
08-31 19:15:25.990  9702  9702 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:5632)
08-31 19:15:25.990  9702  9702 E AndroidRuntime: 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
08-31 19:15:25.990  9702  9702 E AndroidRuntime: 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
08-31 19:15:25.990  9702  9702 E AndroidRuntime: 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
08-31 19:15:25.990  9702  9702 E AndroidRuntime: 	at android.view.View.layout(View.java:17776)
08-31 19:15:25.990  9702  9702 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:5632)
08-31 19:15:25.990  9702  9702 E AndroidRuntime: 	at com.google.android.material.appbar.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:23)
08-31 19:15:25.990  9702  9702 E AndroidRuntime: 	at com.google.android.material.appbar.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:1)
08-31 19:15:25.990  9702  9702 E AndroidRuntime: 	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:8)
08-31 19:15:25.990  9702  9702 E AndroidRuntime: 	at android.view.View.layout(View.java:17776)
08-31 19:15:25.990  9702  9702 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:5632)
08-31 19:15:25.990  9702  9702 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
08-31 19:15:25.990  9702  9702 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
08-31 19:15:25.990  9702  9702 E AndroidRuntime: 	at android.view.View.layout(View.java:17776)
08-31 19:15:25.990  9702  9702 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:5632)
08-31 19:15:25.990  9702  9702 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
08-31 19:15:25.990  9702  9702 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
08-31 19:15:25.990  9702  9702 E AndroidRuntime: 	at android.view.View.layout(View.java:17776)
08-31 19:15:25.990  9702  9702 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:5632)
08-31 19:15:25.990  9702  9702 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
08-31 19:15:25.990  9702  9702 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
08-31 19:15:25.990  9702  9702 E AndroidRuntime: 	at android.view.View.layout(View.java:17776)
08-31 19:15:25.990  9702  9702 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:5632)
08-31 19:15:25.990  9702  9702 E AndroidRuntime: 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
08-31 19:15:25.990  9702  9702 E AndroidRuntime: 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
08-31 19:15:25.990  9702  9702 E AndroidRuntime: 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
08-31 19:15:25.990  9702  9702 E AndroidRuntime: 	at android.view.View.layout(View.java:17776)
08-31 19:15:25.990  9702  9702 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:5632)
08-31 19:15:25.990  9702  9702 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
08-31 19:15:25.990  9702  9702 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
08-31 19:15:25.990  9702  9702 E AndroidRuntime: 	at com.android.internal.policy.DecorView.onLayout(DecorView.java:753)
08-31 19:15:25.990  9702  9702 E AndroidRuntime: 	at android.view.View.layout(View.java:17776)
08-31 19:15:25.990  9702  9702 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:5632)
08-31 19:15:25.990  9702  9702 E AndroidRuntime: 	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2627)
08-31 19:15:25.990  9702  9702 E AndroidRuntime: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2297)
08-31 19:15:25.990  9702  9702 E AndroidRuntime: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1442)
08-31 19:15:25.991  9702  9702 E AndroidRuntime: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6941)
08-31 19:15:25.991  9702  9702 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:878)
08-31 19:15:25.991  9702  9702 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:690)
08-31 19:15:25.991  9702  9702 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:625)
08-31 19:15:25.991  9702  9702 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:864)
08-31 19:15:25.991  9702  9702 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:751)
08-31 19:15:25.991  9702  9702 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
08-31 19:15:25.991  9702  9702 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:185)
08-31 19:15:25.991  9702  9702 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6474)
08-31 19:15:25.991  9702  9702 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
08-31 19:15:25.991  9702  9702 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:916)
08-31 19:15:25.991  9702  9702 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:806)
08-31 19:15:25.998  9702  9702 I Process : Sending signal. PID: 9702 SIG: 9

```

**Comment by alexbakker** [comment]
Thanks for the report, this is a good catch.
